import { IMedia } from '../coop-types'
import { IAuditable, ITimeStamps, TEntityId, TUserType } from '../common'
import { IQrScanResult } from '../qr-result'

// api/v1/authentication/current/user
export interface IUserBase extends ITimeStamps, IAuditable {
    id: TEntityId

    media_id: TEntityId
    media: IMedia // Generated by server

    api_key: string

    password: string
    birthdate?: Date

    user_name: string
    first_name?: string
    middle_name?: string
    last_name?: string
    full_name?: string
    suffix?: string

    email: string
    is_email_verified?: boolean

    type?: TUserType

    contact_number: string
    is_contact_verified?: boolean

    qr_code: IQrScanResult<string, 'user-id'>
}

export interface IOwner extends IUserBase {
    type: 'owner'
}

export interface IEmployee extends IUserBase {
    type: 'employee'
}

export interface IMember extends IUserBase {
    type: 'member'
}
