import { IBranch, IMedia } from '../coop-types'
import { ITimeStamps, TEntityId } from '../common'
import { IOrganization } from '../lands-types/organization'
import { IGeneratedReport } from '../lands-types/generated-report'

export type TUserType = 'member' | 'owner' | 'employee'

// api/v1/authentication/current
export interface IAuthUser {
    user: IUserBase
    organization?: IOrganization
    branch?: IBranch
    reports?: IGeneratedReport[]
}

// api/v1/authentication/current/user
export interface IUserBase extends ITimeStamps {
    // coop | lands
    id: TEntityId // sa loob sa labas na ID? // coop | lands

    media_id: TEntityId
    media: IMedia // Generated by server

    api_key: string

    password: string
    birthdate?: Date

    user_name: string
    first_name?: string
    middle_name?: string
    last_name?: string
    full_name?: string
    suffix?: string

    email: string
    is_email_verified?: boolean

    contact_number: string
    is_contact_verified?: boolean
}

// export interface IUserBase {

// }
