import { Dispatch, SetStateAction } from 'react'

import { create } from 'zustand'

import {
    IGeneralLedger,
    IMemberJointAccount,
    IMemberProfile,
    TEntityId,
    TPaymentMode,
} from '@/types'

export interface TransactionPropsStore {
    openMemberPicker: boolean
    focusTypePayment: TPaymentMode
    selectedMember: IMemberProfile | null
    openPaymentsEntryModal: boolean
    selectedAccountId: TEntityId | undefined
    isAutoGeneratedOR?: boolean
    selectedJointMember?: IMemberJointAccount | null
    openSuccessModal: boolean
    transactionFormSuccess: IGeneralLedger | null
    openPaymentWithTransactionModal: boolean

    setOpenMemberPicker: Dispatch<SetStateAction<boolean>>
    setFocusTypePayment: (payment: TPaymentMode) => void
    setSelectedMember: (member: IMemberProfile | null) => void
    setOpenPaymentsEntryModal: (open: boolean) => void
    setSelectedAccountId: (accountId: TEntityId | undefined) => void
    setIsAutoGeneratedOR: (isAutoGenerated: boolean) => void
    setSelectedJointMember: (jointMember: IMemberJointAccount | null) => void
    setOpenSuccessModal: (open: boolean) => void
    setTransactionFormSuccess: (transaction: IGeneralLedger | null) => void
    setOpenPaymentWithTransactionModal: (open: boolean) => void

    handleResetAll: () => void
}

export const useTransactionStore = create<TransactionPropsStore>(
    (set, get) => ({
        focusTypePayment: 'payment',
        selectedMember: null,
        openPaymentsEntryModal: false,
        openMemberPicker: false,
        selectedAccountId: undefined,
        isAutoGeneratedOR: false,
        selectedJointMember: null,
        openSuccessModal: false,
        transactionFormSuccess: null,
        openPaymentWithTransactionModal: false,

        setSelectedAccountId: (accountId) =>
            set({ selectedAccountId: accountId }),
        setSelectedMember: (member) => set({ selectedMember: member }),
        setOpenPaymentsEntryModal: (open) =>
            set({ openPaymentsEntryModal: open }),
        setFocusTypePayment: (payment) =>
            set({
                focusTypePayment: payment,
                openPaymentWithTransactionModal: true,
            }),
        setOpenMemberPicker: (open) =>
            set({
                openMemberPicker:
                    typeof open === 'function'
                        ? open(get().openMemberPicker)
                        : open,
            }),
        setIsAutoGeneratedOR: (isAutoGenerated) =>
            set({ isAutoGeneratedOR: isAutoGenerated }),
        setSelectedJointMember: (jointMember) =>
            set({ selectedJointMember: jointMember }),
        setOpenSuccessModal: (open) => set({ openSuccessModal: open }),
        setTransactionFormSuccess: (transaction) =>
            set({ transactionFormSuccess: transaction }),
        setOpenPaymentWithTransactionModal: (open) =>
            set({ openPaymentWithTransactionModal: open }),

        handleResetAll: () =>
            set(() => ({
                focusTypePayment: 'payment',
                selectedMember: null,
                openPaymentsEntryModal: false,
                openMemberPicker: false,
                selectedAccountId: undefined,
                isAutoGeneratedOR: false,
                selectedJointMember: null,
                openSuccessModal: false,
                transactionFormSuccess: null,
                openPaymentWithTransactionModal: false,
            })),
    })
)
