export const ICONS = [
    'X',
    'F1',
    'F2',
    'F3',
    'Map',
    'CSV',
    'Sun',
    'Key',
    'Dev',
    'Eye',
    'Tag',
    'Book',
    'View',
    'Stop',
    'Play',
    'Note',
    'Copy',
    'Bank',
    'Plus',
    'Bill',
    'Undo',
    'Redo',
    'User',
    'Moon',
    'Draw',
    'Park',
    'Link',
    'Gear',
    'Hash',
    'Back',
    'Next',
    'Globe',
    'Ghost',
    'Money',
    'Empty',
    'Minus',
    'Error',
    'File X',
    'Trash',
    'Clock',
    'Close',
    'Email',
    'Image',
    'Check',
    'Phone',
    'Excel',
    'Store',
    'Reset',
    'House',
    'Tablet',
    'Unlink',
    'Family',
    'Reload',
    'QR Code',
    'Dot Big',
    'Camera',
    'Layers',
    'FA Bold',
    'Shield',
    'Users 3',
    'Branch',
    'Logout',
    'Export',
    'Zoom In',
    'Adjust',
    'Wallet',
    'School',
    'Image 2',
    'ID Card',
    'Eye View',
    'Not Allowed',
    'Crown',
    'Scan QR',
    'Scan Line',
    'Instagram',
    'Facebook',
    'Linkedin',
    'Code SandBox',
    'Users 3 Fill',
    'References',
    'Column',
    'Column Outline',
    'People Group',
    'Exclude',
    'Receipt',
    'Printer',
    'Percent',
    'Savings',
    'Details',
    'Replace',
    'Warning',
    'Monitor',
    'Options',
    'User Cog',
    'Genders',
    'Refresh',
    'Arrow Up',
    'Sidebar',
    'Sun Moon',
    'Zoom Out',
    'Village',
    'Reports',
    'Push Pin',
    'Eye None',
    'User Tag',
    'User Plus',
    'FA Check',
    'FA Times',
    'Shield Fill',
    'Arrow Up Long',
    'Landmark',
    'Sign Post',
    'Internal',
    'User Lock',
    'Language',
    'Book Open',
    'Price Tag',
    'Pie Chart',
    'Accounts',
    'Payments',
    'Home Fill',
    'Facebook',
    'QUestion',
    'Question Circle',
    'Settings',
    'User List',
    'Messages',
    'Feedback',
    'Building',
    'Download',
    'Calendar',
    'File Fill',
    'Users Add',
    'Exit Door',
    'Exit Door Fill',
    'Tree City',
    'Key Sharp',
    'Money Bag',
    'Check Fill',
    'Hand Coins',
    'Map Marked',
    'Code Block',
    'Arrow Left',
    'Brief Case',
    'Arrow Down',
    'Book Stack',
    'Camera Off',
    'Dot Medium',
    'Footsteps',
    'User Clock',
    'Dashboard',
    'IoIosCode',
    'Wood Signs',
    'Telephone',
    'User Group',
    'House Lock',
    'Row Spacing',
    'Checks Grid',
    'Navigation',
    'Shield Lock',
    'Money Stack',
    'Money Check',
    'Folder Fill',
    'Collapse All',
    'Arrow Right',
    'Coins Stack',
    'Smartphone',
    'Pencil Fill',
    'Small Brush',
    'Fullscreen',
    'Rotate Left',
    'Power Reset',
    'Paper Plane',
    'Block Quote',
    'Drag Handle',
    'Camera Fill',
    'Edit Pencil',
    'Badge Minus',
    'Badge Check',
    'Email Check',
    'Camera Flip',
    'Credit Card',
    'User Shield',
    'Weight Scale',
    'Target Arrow',
    'Money Check 2',
    'Desktop Tower',
    'Chat Bubbles',
    'Credit Card 2',
    'Pin Location',
    'Unavailable',
    'Maintenance',
    'Warning Fill',
    'Shield Check',
    'Address Card',
    'Arrow Up Down',
    'Chevron Left',
    'Sidebar Left',
    'Building Cog',
    'List Ordered',
    'Rotate Right',
    'Location Pin',
    'Hand Deposit',
    'Chevron Down',
    'PDF File Fill',
    'Bank DuoTone',
    'Barcode Scan',
    'Organization',
    'Curly Bracket',
    'Calendar Dots',
    'Bracket Error',
    'Arrow Trend Up',
    'Boxes Stacked',
    'Notification',
    'Chevrons Left',
    'Text File Fill',
    'Phone Outline',
    'Flip Vertical',
    'Funnel Filled',
    'Push Pin Slash',
    'Dots Vertical',
    'Chevron Right',
    'Camera Select',
    'Sidebar Right',
    'Hand Withdraw',
    'Arrow Chevron Down',
    'GiMoney Stack',
    'Account Setup',
    'Badge Question',
    'Video File Fill',
    'Music File Fill',
    'Image File Fill',
    'Excel File Fill',
    'Graduation Cap',
    'Rotate Box Left',
    'Toolbar Italic',
    'Chevrons Right',
    'Funnel Outline',
    'Calendar Check',
    'Warning Circle',
    'Verified Patch',
    'Online Payment',
    'Loading Circle',
    'Pencil Outline',
    'User Clock Fill',
    'Comment Dashed',
    'Arrow Chevron Right',
    'Finance Reports',
    'Layers Sharp Dot',
    'Signature Light',
    'Hand Shake Heart',
    'Flip Horizontal',
    'Hand Drop Coins',
    'Rotate Box Right',
    'Badge Check Fill',
    'Badge Minus Fill',
    'Building Branch',
    'Loading Spinner',
    'Chevrons Up Down',
    'Account Setting',
    'Fullscreen Exit',
    'Message Outline',
    'Heart Break Fill',
    'Brief Case Clock',
    'Plug Connect Fill',
    'FA Calendar Check',
    'Magnifying Glass',
    'Spread Sheet File',
    'Hard Drive Upload',
    'List Bullets Bold',
    'Mixer Horizontal',
    'Transaction List',
    'Dash Square Dotted',
    'Open External Link',
    'Flip Vertical Line',
    'Badge Exclamation',
    'Document File Fill',
    'Shield Exclamation',
    'Badge Question Fill',
    'Location Pin Outline',
    'Question Circle Fill',
    'Horizontal Rule Icon',
    'Flip Horizontal Line',
    'Rotate 90 Degree Left',
    'Rotate 90 Degree Right',
    'Badge Exclamation Fill',
    'Text Strikethrough Light',
    'Twitter',
    'Youtube',
    'Hands Helping',
    'Bordered Shield Icon',
    'Gi Clock Icon',
    'Ri Community Fill Icon',
] as const
