export const ICONS = [
    'Robot',
    'Rocket',
    'Pulse',
    'SidebarLeft',
    'ArrowChevronUp',
    'GripHorizontal',
    'GripVertical',
    'Circle',
    'Pipette',
    'Headset',
    'Heading',
    'Code Icon',
    'X',
    'F1',
    'F2',
    'F3',
    'Map',
    'CSV',
    'Sun',
    'Key',
    'Dev',
    'Eye',
    'Tag',
    'Book',
    'View',
    'Stop',
    'Play',
    'Note',
    'Copy',
    'Bank',
    'Plus',
    'Bill',
    'Undo',
    'Redo',
    'User',
    'Moon',
    'Draw',
    'Park',
    'Link',
    'Gear',
    'Hash',
    'Back',
    'Next',
    'Info',
    'Globe',
    'Ghost',
    'Money',
    'Empty',
    'Minus',
    'Error',
    'File X',
    'Trash',
    'Clock',
    'Close',
    'Bug',
    'Email',
    'Image',
    'Check',
    'Phone',
    'Excel',
    'Store',
    'Reset',
    'House',
    'Tablet',
    'Unlink',
    'Family',
    'Reload',
    'QR Code',
    'Youtube',
    'Dot Big',
    'Camera',
    'Layers',
    'FA Bold',
    'Shield',
    'Users 3',
    'Branch',
    'Logout',
    'Export',
    'Zoom In',
    'Adjust',
    'Wallet',
    'School',
    'Image 2',
    'ID Card',
    'Eye View',
    'Eye Off',
    'Not Allowed',
    'Crown',
    'Scan QR',
    'Scan Line',
    'Instagram',
    'Facebook',
    'Book Thick',
    'Linkedin',
    'Shapes',
    'Code SandBox',
    'Users 3 Fill',
    'Users 3 Line',
    'References',
    'Column',
    'Column Outline',
    'People Group',
    'Running',
    'Paint Brush',
    'Wand Sparkle',
    'Devices',
    'Exclude',
    'Receipt',
    'Printer',
    'Percent',
    'Ticket',
    'Calendar Number',
    'Money Trend',
    'Trend Up',
    'Printer Fill',
    'Judge Hammer',
    'Umbrella',
    'PiggyBank',
    'Sparkle',
    'Star',
    'Swap Arrow',
    'Thumbs Up',
    'Thumbs Down',
    'Cake',
    'Trend Down',
    'Calculator',
    'Savings',
    'Details',
    'Replace',
    'Warning',
    'Twitter',
    'Monitor',
    'Options',
    'User Cog',
    'Genders',
    'Refresh',
    'Arrow Up',
    'Sidebar',
    'Sun Moon',
    'Zoom Out',
    'Village',
    'Reports',
    'Push Pin',
    'Eye None',
    'User Tag',
    'User Plus',
    'FA Check',
    'FA Times',
    'Shield Fill',
    'Arrow Up Long',
    'Landmark',
    'Sign Post',
    'Internal',
    'User Lock',
    'Language',
    'Book Open',
    'Price Tag',
    'Pie Chart',
    'Accounts',
    'Payments',
    'Home Fill',
    'Facebook',
    'QUestion',
    'Question Circle',
    'Settings',
    'User List',
    'Messages',
    'Feedback',
    'Building',
    'Download',
    'Calendar',
    'File Fill',
    'Users Add',
    'Exit Door',
    'Exit Door Fill',
    'Tree City',
    'Key Sharp',
    'Money Bag',
    'Check Fill',
    'Hand Coins',
    'Map Marked',
    'Code Block',
    'Arrow Left',
    'Brief Case',
    'Arrow Down',
    'Book Stack',
    'Camera Off',
    'Dot Medium',
    'Footsteps',
    'User Clock',
    'Dashboard',
    'IoIosCode',
    'Wood Signs',
    'Telephone',
    'User Group',
    'House Lock',
    'Row Spacing',
    'Checks Grid',
    'Navigation',
    'Shield Lock',
    'Money Stack',
    'Money Check',
    'Folder Fill',
    'Collapse All',
    'Arrow Right',
    'Coins Stack',
    'Smartphone',
    'Pencil Fill',
    'Small Brush',
    'Fullscreen',
    'Rotate Left',
    'Power Reset',
    'Paper Plane',
    'Block Quote',
    'Drag Handle',
    'Camera Fill',
    'Edit Pencil',
    'Badge Minus',
    'Badge Check',
    'Email Check',
    'Camera Flip',
    'Credit Card',
    'User Shield',
    'Weight Scale',
    'Target Arrow',
    'Money Check 2',
    'Desktop Tower',
    'Chat Bubbles',
    'Credit Card 2',
    'Pin Location',
    'Unavailable',
    'Maintenance',
    'Upload Icon',
    'Warning Fill',
    'Shield Check',
    'Address Card',
    'Arrow Up Down',
    'Chevron Left',
    'Sidebar Left',
    'Building Cog',
    'Expand Less',
    'Expand More',
    'List Ordered',
    'Rotate Right',
    'Location Pin',
    'Hand Deposit',
    'Chevron Down',
    'PDF File Fill',
    'Bank DuoTone',
    'Gi Clock Icon',
    'Barcode Scan',
    'Organization',
    'Curly Bracket',
    'Plant Growth',
    'Calendar Dots',
    'Bracket Error',
    'Arrow Trend Up',
    'Boxes Stacked',
    'Notification',
    'Chevrons Left',
    'Text File Fill',
    'Phone Outline',
    'Flip Vertical',
    'Funnel Filled',
    'Push Pin Slash',
    'Dots Vertical',
    'Chevron Right',
    'Camera Select',
    'Hands Helping',
    'Sidebar Right',
    'Building Gear',
    'Hand Withdraw',
    'Arrow Chevron Down',
    'GiMoney Stack',
    'Account Setup',
    'Badge Question',
    'Video File Fill',
    'Music File Fill',
    'Image File Fill',
    'Excel File Fill',
    'Graduation Cap',
    'Rotate Box Left',
    'Toolbar Italic',
    'Chevrons Right',
    'Funnel Outline',
    'Calendar Check',
    'Warning Circle',
    'Verified Patch',
    'Online Payment',
    'Loading Circle',
    'Pencil Outline',
    'User Clock Fill',
    'Comment Dashed',
    'Pi Hand Withdraw',
    'Finance Reports',
    'Layers Sharp Dot',
    'Signature Light',
    'Hand Shake Heart',
    'Lu History Icon',
    'Flip Horizontal',
    'Hand Drop Coins',
    'Rotate Box Right',
    'Badge Check Fill',
    'Badge Minus Fill',
    'Building Branch',
    'Loading Spinner',
    'Chevrons Up Down',
    'Account Setting',
    'Fullscreen Exit',
    'Message Outline',
    'Heart Break Fill',
    'Brief Case Clock',
    'Plug Connect Fill',
    'FA Calendar Check',
    'Magnifying Glass',
    'Spread Sheet File',
    'Hard Drive Upload',
    'List Bullets Bold',
    'Error Exclamation',
    'Mixer Horizontal',
    'Outline Payment',
    'Pi Hand Deposit',
    'Transaction List',
    'Arrow Chevron Right',
    'Dash Square Dotted',
    'Open External Link',
    'Flip Vertical Line',
    'Badge Exclamation',
    'Document File Fill',
    'Shield Exclamation',
    'Badge Question Fill',
    'Bordered Shield Icon',
    'Location Pin Outline',
    'Question Circle Fill',
    'Horizontal Rule Icon',
    'Flip Horizontal Line',
    'Rotate 90 Degree Left',
    'Rotate 90 Degree Right',
    'Badge Exclamation Fill',
    'Text Strikethrough Light',
    'Ri Community Fill Icon',
    'Auto Awesome',
    'Arrow Icon',
    'Redo Circle Icon',
    'Focus Icon',
    'Command Icon',
    'Clock Cancel',
<<<<<<< Updated upstream
=======
    'Wrench Icon',
    'Draft Icon',
>>>>>>> Stashed changes
] as const
