import { useCallback } from 'react'

import { useNavigate } from '@tanstack/react-router'
import { useForm } from 'react-hook-form'
import { toast } from 'sonner'

import { standardSchemaResolver } from '@hookform/resolvers/standard-schema'

import { IGeneralLedger } from '@/modules/general-ledger'
import {
    TTransactionFormSchema,
    TransactionFromSchema,
    useGetTransactionById,
} from '@/modules/transaction'
import { useTransactionBatchStore } from '@/modules/transaction-batch/store/transaction-batch-store'
import { useTransactionReverseSecurityStore } from '@/store/transaction-reverse-security-store'
import { useHotkeys } from 'react-hotkeys-hook'

import { useSubscribe } from '@/hooks/use-pubsub'
import { useQeueryHookCallback } from '@/hooks/use-query-hook-cb'

import { TEntityId } from '@/types'

import { useTransactionModals } from './use-transaction-modals'

const useTransactionNavigation = (fullPath: string) => {
    const navigate = useNavigate()
    return {
        open: (id: TEntityId) =>
            navigate({ to: fullPath, search: { transactionId: id } }),
        clear: () => navigate({ to: fullPath, search: {} }),
    }
}

export type UseTransactionControllerProps = {
    fullPath: string
    transactionId: TEntityId
    newOR: string
    isAutoGenerated: boolean
}

export const useTransactionController = ({
    transactionId,
    fullPath,
    newOR,
    isAutoGenerated,
}: UseTransactionControllerProps) => {
    const navigate = useTransactionNavigation(fullPath)

    const modals = useTransactionModals()

    const { hasNoTransactionBatch, data: currentTransactionBatch } =
        useTransactionBatchStore()

    const transactionReverse = useTransactionReverseSecurityStore()

    const form = useForm<TTransactionFormSchema>({
        resolver: standardSchemaResolver(TransactionFromSchema),
        defaultValues: {
            reference_number: newOR,
            or_auto_generated: isAutoGenerated,
            member_profile: undefined,
            member_profile_id: undefined,
            general_ledger_id: undefined,
        },
    })

    const selectedMember = form.getValues('member_profile')

    const {
        data: getTransaction,
        isError,
        isSuccess,
        refetch: refetchTransaction,
        isLoading:isLoadingTransaction
    } = useGetTransactionById({
        id: transactionId,

        options: { retry: 1, enabled: !!transactionId, retryDelay: 50 },
    })

    const handleError = useCallback((error: Error) => {
        toast.error(error?.message || 'Something went wrong')
    }, [])

    useQeueryHookCallback({
        data: getTransaction,
        error: handleError,
        isError: isError,
        isSuccess: isSuccess,
        onSuccess: (transaction) => {
            form.setValue('member_profile', transaction.member_profile)
            form.setValue('member_profile_id', transaction.member_profile_id)
        },
    })
    useSubscribe(
        `member_occupation_history.create.member_profile.${selectedMember}`
    )
    useSubscribe(
        `member_occupation_history.update.member_profile.${selectedMember}`
    )
    useSubscribe(
        `member_occupation_history.delete.member_profile.${selectedMember}`
    )
    useSubscribe(`transaction.create.${transactionId}`)
    useSubscribe(`transaction.update.${transactionId}`)

    useHotkeys(
        'Escape',
        (e) => {
            e.preventDefault()
            form.reset()
            navigate.clear()
        },
        { enableOnFormTags: true },
        [form, navigate.clear]
    )

    return {
        transactionId,
        fullPath,
        transaction: getTransaction,
        getTransaction,
        navigate,
        handlers: {
            handleRemoveMember: () => {
                form.setValue('member_profile', undefined)
                form.setValue('member_profile_id', undefined)
            },
            resetForm: () => {
                form.reset()
            },
        },
        hasNoTransactionBatch,
        currentTransactionBatch,
        ...transactionReverse,
        form,
        ...modals,
        selectedMemberId: form.getValues('member_profile_id'),
        refetchTransaction,
        generalLedger: form.getValues('general_ledger') as IGeneralLedger,
        isLoadingTransaction
    }
}

export type TTransactionControllerReturn = ReturnType<
    typeof useTransactionController
>
