import { useCallback, useState } from 'react'

import { useQueryClient } from '@tanstack/react-query'
import { useNavigate } from '@tanstack/react-router'
import { UseFormReturn, useForm } from 'react-hook-form'

import { standardSchemaResolver } from '@hookform/resolvers/standard-schema'

import { IGeneralLedger } from '@/modules/general-ledger'
import {
    TTransactionFormSchema,
    TransactionFromSchema,
    useGetTransactionById,
} from '@/modules/transaction'
import { useTransactionBatchStore } from '@/modules/transaction-batch/store/transaction-batch-store'
import { IUserOrganization } from '@/modules/user-organization'
import { useTransactionReverseSecurityStore } from '@/store/transaction-reverse-security-store'
import { useHotkeys } from 'react-hotkeys-hook'

import { useModalState } from '@/hooks/use-modal-state'

import { TEntityId } from '@/types'

import { useTransactionContext } from '../context/transaction-context'
import { paymentORResolver } from '../transaction.utils'

const useTransactionNavigation = (fullPath: string) => {
    const navigate = useNavigate()
    return {
        open: (id: TEntityId) =>
            navigate({ to: fullPath, search: { transactionId: id } }),
        clear: () => navigate({ to: fullPath, search: {} }),
    }
}

export type UseTransactionControllerProps = {
    fullPath: string
    transactionId: TEntityId
    form: UseFormReturn<TTransactionFormSchema>
    userOrganization: IUserOrganization
    payment_or_allow_user_input: boolean
    ORWithPadding: string
}

export const useTransactionController = ({
    transactionId,
    fullPath,
    form,
    modals,
}: UseTransactionControllerProps & {
    modals: ReturnType<typeof useTransactionModals>
}) => {
    const queryClient = useQueryClient()
    const navigate = useTransactionNavigation(fullPath)
    const [transaction, setTransaction] = useState<IGeneralLedger | undefined>()

    const { hasNoTransactionBatch, data: currentTransactionBatch } =
        useTransactionBatchStore()
    const transactionReverse = useTransactionReverseSecurityStore()

    // Handlers
    const onPaymentSuccess = useCallback(
        (data: IGeneralLedger) => {
            if (!data) return
            setTransaction(data)
            modals.success.onOpenChange(true)

            form.reset(
                {
                    ...form.getValues(),
                    member_profile: data.member_profile,
                    member_profile_id: data.member_profile_id,
                },
                { keepDirty: false }
            )

            queryClient.invalidateQueries({ queryKey: ['transaction'] })
        },
        [form, modals.success, queryClient]
    )

    useHotkeys(
        'Escape',
        (e) => {
            e.preventDefault()
            form.reset()
            navigate.clear()
        },
        { enableOnFormTags: true }
    )

    // Data Fetching
    const { data: getTransaction } = useGetTransactionById({
        id: transactionId,
        options: { enabled: !!transactionId },
    })

    return {
        transactionId,
        fullPath,
        transaction,
        getTransaction,
        navigate,
        handlers: {
            onPaymentSuccess,
            handleRemoveMember: () =>
                form.setValue('member_profile', undefined),
            resetForm: () => form.reset(),
        },
        hasNoTransactionBatch,
        currentTransactionBatch,
        ...transactionReverse,
        handleRemoveMember: () => {},
    }
}

interface UseTransactionFormLogicProps {
    userOrganization: IUserOrganization
    payment_or_allow_user_input: boolean
    ORWithPadding: string
}

interface UseTransactionFormLogicReturn {
    form: UseFormReturn<TTransactionFormSchema>
    syncOR: () => void
}

export const useTransactionFormLogic = ({
    userOrganization,
    payment_or_allow_user_input,
    ORWithPadding,
}: UseTransactionFormLogicProps): UseTransactionFormLogicReturn => {
    const form = useForm<TTransactionFormSchema>({
        resolver: standardSchemaResolver(TransactionFromSchema),
        defaultValues: {
            reference_number: paymentORResolver(userOrganization),
            or_auto_generated: !payment_or_allow_user_input,
            member_profile: undefined,
            member_profile_id: undefined,
            // Add other schema defaults here...
        },
    })
    const syncOR = useCallback(() => {
        const isAutoGenerated = !payment_or_allow_user_input

        form.setValue('or_auto_generated', isAutoGenerated)

        if (isAutoGenerated) {
            form.setValue(
                'reference_number',
                paymentORResolver(userOrganization)
            )
        } else {
            form.setValue('reference_number', ORWithPadding)
        }
    }, [form, userOrganization, payment_or_allow_user_input, ORWithPadding])

    return {
        form,
        syncOR,
    }
}

export const useTransactionModals = () => {
    return {
        success: useModalState(),
        accountPicker: useModalState(),
        memberScanner: useModalState(),
        ledger: useModalState(),
        accountPayment: useModalState(),
        loanPayment: useModalState(),
        othersCollapsible: useModalState(),
    }
}

export const useHotkeysTransaction = () => {
    const {
        navigate,
        selectedMemberId,
        handlers: { resetTransactionForm },
        form: transactionForm,
        modals: { memberScanner },
        payment_or_allow_user_input,
        ORWithPadding,
        userOrganization,
    } = useTransactionContext()

    useHotkeys(
        'Escape',
        (e) => {
            e.preventDefault()
            resetTransactionForm()
            navigate.clear()
        },
        { enableOnFormTags: true },
        [resetTransactionForm, navigate.open]
    )

    useHotkeys(
        'Enter',
        (e) => {
            e.preventDefault()
            if (!selectedMemberId && !memberScanner.open) {
                console.log('enter')
                memberScanner.onOpenChange(true)
            }
        },
        { enableOnFormTags: true },
        [selectedMemberId, memberScanner.open]
    )

    useHotkeys(
        'Alt + W',
        (e) => {
            e.preventDefault()
            transactionForm.setFocus('reference_number')
        },
        { enableOnFormTags: true },
        [transactionForm]
    )
    useHotkeys(
        'Alt +  E',
        (e) => {
            e.preventDefault()
            const isAuto = !transactionForm.getValues('or_auto_generated')
            transactionForm.setValue('or_auto_generated', isAuto)
            if (isAuto && userOrganization) {
                transactionForm.setValue(
                    'reference_number',
                    paymentORResolver(userOrganization)
                )
            }
        },
        { enableOnFormTags: true },
        [transactionForm, userOrganization]
    )
}
