import {
    GeneratedReportTemplate,
    IBaseReportTemplateCheck,
    IBaseReportTemplateData,
} from '@/modules/generated-report'

import { TMemberListingSchema } from '../components/forms/member-listing-create-report-form'
import MEMBER_LISTING_IDENTITY_BIO_T1 from './templates/member-listing-templates/mmbr-lstng-bio-t1.njk?raw'
import MEMBER_LISTING_COMPLIANCE_TIN_T1 from './templates/member-listing-templates/mmbr-lstng-compliance-tin-t1.njk?raw'
import MEMBER_LISTING_DETAILED_LOC_T1 from './templates/member-listing-templates/mmbr-lstng-detailed-loc-t1.njk?raw'
import MEMBER_LISTING_SUMMARY_STAT_T1 from './templates/member-listing-templates/mmbr-lstng-summary-stat-t1.njk?raw'

// START DO NOT EDIT
type TPresentationStyle =
    | 'identity_bio' // format 1: Core membership data + birth details
    | 'summary_stat' // format 2: Demographic overview (age/occupation)
    | 'compliance_tin' // format 3: Official registry with tax identification
    | 'detailed_loc' // format 4: Full directory with address and contact

export interface IMemberListingReportTemplate
    extends IBaseReportTemplateData, IBaseReportTemplateCheck {
    // for header
    date_filter_mode?: TMemberListingSchema['date_filter_mode'] // 'membership_date', 'birth_date'
    // either of these two is group by
    start_date: string // depends on date_filter_mode, if undefined show // all membership date
    end_date: string // depends on date_filter_mode, if undefined show // all birth date

    group_by: TMemberListingSchema['group_by']

    // Controls which grouped-entry columns are expected by the presenter.
    presentation_style?: TPresentationStyle

    report_type: TMemberListingSchema['report_type'] // 'summary', 'detail'

    // grouping haeder (for example by member type or barangay).
    group_data_entry: Array<{
        group_title?: string // Group section title (member type, barangay, etc.).

        group_by_data_entries: Array<{
            group_by_title: string // Selected group_by bucket value.

            // Entries under the selected group_by bucket.
            group_by_data_entries: Array<{
                // identity_bio, summary_stat, compliance_tin, detailed_loc
                passbook?: string

                sex?: string // identity_bio, compliance_tin
                name?: string // identity_bio, compliance_tin, detailed_loc
                membership_date?: string // identity_bio, compliance_tin, detailed_loc
                birth_date?: string // identity_bio
                address?: string // detailed_loc

                age?: string | number // summary_stat
                gender?: string // summary_stat, detailed_loc
                occupation?: string // summary_stat, detailed_loc

                tin?: string | number // compliance_tin, detailed_loc
                phone_number?: string | number // identity_bio, compliance_tin, detailed_loc
            }>
            group_male_total_members?: string | number // only used when summary report type
            group_female_total_members?: string | number // only used when summary report type
            group_total_non_male_female?: string | number // only used when summary report type
            group_by_sub_total_members?: string | number //  can be used when summary report type
        }>
        group_total_members?: string | number

        // Used for final-page grand total summary. or can be used to display if summary report type
        group_male_total_members?: string | number
        group_female_total_members?: string | number
        group_total_non_male_female?: string | number
        group_total?: string | number
    }>

    // Used for final-page grand total summary.
    total_male?: string | number
    total_female?: string | number
    total_non_male_female?: string | number
    total_member?: string | number
}
// END DO NOT EDIT

export const SHARED_MEMBER_LISTING_PREVIEW_DATA: IMemberListingReportTemplate =
    {
        header_title: 'SAMPLE COOPERATIVE',
        header_address: '123 Main Street, Sample City',
        tax_number: '000-000-000-000',
        report_title: 'MEMBER LISTING REPORT',

        start_date: '2026-01-01',
        end_date: '2026-03-31',

        date_filter_mode: 'membership_date',
        report_type: 'detail',
        group_by: 'month',
        presentation_style: 'identity_bio',

        group_data_entry: [
            {
                group_title: 'REGULAR MEMBERS',
                group_by_data_entries: [
                    {
                        group_by_title: 'JANUARY 2026',
                        group_by_data_entries: [
                            {
                                passbook: 'PB-0001',
                                sex: 'M',
                                name: 'Juan Dela Cruz',
                                membership_date: '2026-01-01',
                                birth_date: '1988-01-01',
                                address: 'San Isidro, Purok 1, Sample City',
                                tin: '101-201-301-401',
                                phone_number: '09171000001',
                                gender: 'Male',
                                age: 24,
                                occupation: 'Farmer',
                            },
                            {
                                passbook: 'PB-0002',
                                sex: 'F',
                                name: 'Maria Santos',
                                membership_date: '2026-01-02',
                                birth_date: '1989-02-03',
                                address: 'San Isidro, Purok 2, Sample City',
                                tin: '102-202-302-402',
                                phone_number: '09171000002',
                                gender: 'Female',
                                age: 25,
                                occupation: 'Vendor',
                            },
                            {
                                passbook: 'PB-0003',
                                sex: 'M',
                                name: 'Pedro Reyes',
                                membership_date: '2026-01-03',
                                birth_date: '1990-03-05',
                                address: 'San Isidro, Purok 3, Sample City',
                                tin: '103-203-303-403',
                                phone_number: '09171000003',
                                gender: 'Male',
                                age: 26,
                                occupation: 'Driver',
                            },
                            {
                                passbook: 'PB-0004',
                                sex: 'F',
                                name: 'Liza Ramos',
                                membership_date: '2026-01-04',
                                birth_date: '1991-04-07',
                                address: 'San Isidro, Purok 4, Sample City',
                                tin: '104-204-304-404',
                                phone_number: '09171000004',
                                gender: 'Female',
                                age: 27,
                                occupation: 'Teacher',
                            },
                            {
                                passbook: 'PB-0005',
                                sex: 'M',
                                name: 'Arman Bautista',
                                membership_date: '2026-01-05',
                                birth_date: '1992-05-09',
                                address: 'San Isidro, Purok 5, Sample City',
                                tin: '105-205-305-405',
                                phone_number: '09171000005',
                                gender: 'Male',
                                age: 28,
                                occupation: 'Mechanic',
                            },
                            {
                                passbook: 'PB-0006',
                                sex: 'F',
                                name: 'Ana Lopez',
                                membership_date: '2026-01-06',
                                birth_date: '1993-06-11',
                                address: 'San Isidro, Purok 6, Sample City',
                                tin: '106-206-306-406',
                                phone_number: '09171000006',
                                gender: 'Female',
                                age: 29,
                                occupation: 'Entrepreneur',
                            },
                            {
                                passbook: 'PB-0007',
                                sex: 'M',
                                name: 'Carlos Mendoza',
                                membership_date: '2026-01-07',
                                birth_date: '1994-07-13',
                                address: 'San Isidro, Purok 7, Sample City',
                                tin: '107-207-307-407',
                                phone_number: '09171000007',
                                gender: 'Male',
                                age: 30,
                                occupation: 'Store Owner',
                            },
                            {
                                passbook: 'PB-0008',
                                sex: 'F',
                                name: 'Rose Villanueva',
                                membership_date: '2026-01-08',
                                birth_date: '1995-08-15',
                                address: 'San Isidro, Purok 8, Sample City',
                                tin: '108-208-308-408',
                                phone_number: '09171000008',
                                gender: 'Female',
                                age: 31,
                                occupation: 'Office Clerk',
                            },
                            {
                                passbook: 'PB-0009',
                                sex: 'M',
                                name: 'Ramon Garcia',
                                membership_date: '2026-01-09',
                                birth_date: '1996-09-17',
                                address: 'San Isidro, Purok 9, Sample City',
                                tin: '109-209-309-409',
                                phone_number: '09171000009',
                                gender: 'Male',
                                age: 32,
                                occupation: 'Carpenter',
                            },
                            {
                                passbook: 'PB-0010',
                                sex: 'F',
                                name: 'Grace Navarro',
                                membership_date: '2026-01-10',
                                birth_date: '1997-10-19',
                                address: 'San Isidro, Purok 10, Sample City',
                                tin: '110-210-310-410',
                                phone_number: '09171000010',
                                gender: 'Female',
                                age: 33,
                                occupation: 'Nurse',
                            },
                        ],
                        group_male_total_members: 5,
                        group_female_total_members: 5,
                        group_total_non_male_female: 0,
                        group_by_sub_total_members: 10,
                    },
                    {
                        group_by_title: 'FEBRUARY 2026',
                        group_by_data_entries: [
                            {
                                passbook: 'PB-0011',
                                sex: 'M',
                                name: 'Juan Dela Cruz',
                                membership_date: '2026-02-01',
                                birth_date: '1988-01-01',
                                address: 'Riverside, Purok 1, Sample City',
                                tin: '111-211-311-411',
                                phone_number: '09171000011',
                                gender: 'Male',
                                age: 24,
                                occupation: 'Farmer',
                            },
                            {
                                passbook: 'PB-0012',
                                sex: 'F',
                                name: 'Maria Santos',
                                membership_date: '2026-02-02',
                                birth_date: '1989-02-03',
                                address: 'Riverside, Purok 2, Sample City',
                                tin: '112-212-312-412',
                                phone_number: '09171000012',
                                gender: 'Female',
                                age: 25,
                                occupation: 'Vendor',
                            },
                            {
                                passbook: 'PB-0013',
                                sex: 'M',
                                name: 'Pedro Reyes',
                                membership_date: '2026-02-03',
                                birth_date: '1990-03-05',
                                address: 'Riverside, Purok 3, Sample City',
                                tin: '113-213-313-413',
                                phone_number: '09171000013',
                                gender: 'Male',
                                age: 26,
                                occupation: 'Driver',
                            },
                            {
                                passbook: 'PB-0014',
                                sex: 'F',
                                name: 'Liza Ramos',
                                membership_date: '2026-02-04',
                                birth_date: '1991-04-07',
                                address: 'Riverside, Purok 4, Sample City',
                                tin: '114-214-314-414',
                                phone_number: '09171000014',
                                gender: 'Female',
                                age: 27,
                                occupation: 'Teacher',
                            },
                            {
                                passbook: 'PB-0015',
                                sex: 'M',
                                name: 'Arman Bautista',
                                membership_date: '2026-02-05',
                                birth_date: '1992-05-09',
                                address: 'Riverside, Purok 5, Sample City',
                                tin: '115-215-315-415',
                                phone_number: '09171000015',
                                gender: 'Male',
                                age: 28,
                                occupation: 'Mechanic',
                            },
                            {
                                passbook: 'PB-0016',
                                sex: 'F',
                                name: 'Ana Lopez',
                                membership_date: '2026-02-06',
                                birth_date: '1993-06-11',
                                address: 'Riverside, Purok 6, Sample City',
                                tin: '116-216-316-416',
                                phone_number: '09171000016',
                                gender: 'Female',
                                age: 29,
                                occupation: 'Entrepreneur',
                            },
                            {
                                passbook: 'PB-0017',
                                sex: 'M',
                                name: 'Carlos Mendoza',
                                membership_date: '2026-02-07',
                                birth_date: '1994-07-13',
                                address: 'Riverside, Purok 7, Sample City',
                                tin: '117-217-317-417',
                                phone_number: '09171000017',
                                gender: 'Male',
                                age: 30,
                                occupation: 'Store Owner',
                            },
                            {
                                passbook: 'PB-0018',
                                sex: 'F',
                                name: 'Rose Villanueva',
                                membership_date: '2026-02-08',
                                birth_date: '1995-08-15',
                                address: 'Riverside, Purok 8, Sample City',
                                tin: '118-218-318-418',
                                phone_number: '09171000018',
                                gender: 'Female',
                                age: 31,
                                occupation: 'Office Clerk',
                            },
                            {
                                passbook: 'PB-0019',
                                sex: 'M',
                                name: 'Ramon Garcia',
                                membership_date: '2026-02-09',
                                birth_date: '1996-09-17',
                                address: 'Riverside, Purok 9, Sample City',
                                tin: '119-219-319-419',
                                phone_number: '09171000019',
                                gender: 'Male',
                                age: 32,
                                occupation: 'Carpenter',
                            },
                            {
                                passbook: 'PB-0020',
                                sex: 'F',
                                name: 'Grace Navarro',
                                membership_date: '2026-02-10',
                                birth_date: '1997-10-19',
                                address: 'Riverside, Purok 10, Sample City',
                                tin: '120-220-320-420',
                                phone_number: '09171000020',
                                gender: 'Female',
                                age: 33,
                                occupation: 'Nurse',
                            },
                        ],
                        group_male_total_members: 5,
                        group_female_total_members: 5,
                        group_total_non_male_female: 0,
                        group_by_sub_total_members: 10,
                    },
                    {
                        group_by_title: 'MARCH 2026',
                        group_by_data_entries: [
                            {
                                passbook: 'PB-0021',
                                sex: 'M',
                                name: 'Juan Dela Cruz',
                                membership_date: '2026-03-01',
                                birth_date: '1988-01-01',
                                address: 'Northville, Purok 1, Sample City',
                                tin: '121-221-321-421',
                                phone_number: '09171000021',
                                gender: 'Male',
                                age: 24,
                                occupation: 'Farmer',
                            },
                            {
                                passbook: 'PB-0022',
                                sex: 'F',
                                name: 'Maria Santos',
                                membership_date: '2026-03-02',
                                birth_date: '1989-02-03',
                                address: 'Northville, Purok 2, Sample City',
                                tin: '122-222-322-422',
                                phone_number: '09171000022',
                                gender: 'Female',
                                age: 25,
                                occupation: 'Vendor',
                            },
                            {
                                passbook: 'PB-0023',
                                sex: 'M',
                                name: 'Pedro Reyes',
                                membership_date: '2026-03-03',
                                birth_date: '1990-03-05',
                                address: 'Northville, Purok 3, Sample City',
                                tin: '123-223-323-423',
                                phone_number: '09171000023',
                                gender: 'Male',
                                age: 26,
                                occupation: 'Driver',
                            },
                            {
                                passbook: 'PB-0024',
                                sex: 'F',
                                name: 'Liza Ramos',
                                membership_date: '2026-03-04',
                                birth_date: '1991-04-07',
                                address: 'Northville, Purok 4, Sample City',
                                tin: '124-224-324-424',
                                phone_number: '09171000024',
                                gender: 'Female',
                                age: 27,
                                occupation: 'Teacher',
                            },
                            {
                                passbook: 'PB-0025',
                                sex: 'M',
                                name: 'Arman Bautista',
                                membership_date: '2026-03-05',
                                birth_date: '1992-05-09',
                                address: 'Northville, Purok 5, Sample City',
                                tin: '125-225-325-425',
                                phone_number: '09171000025',
                                gender: 'Male',
                                age: 28,
                                occupation: 'Mechanic',
                            },
                            {
                                passbook: 'PB-0026',
                                sex: 'F',
                                name: 'Ana Lopez',
                                membership_date: '2026-03-06',
                                birth_date: '1993-06-11',
                                address: 'Northville, Purok 6, Sample City',
                                tin: '126-226-326-426',
                                phone_number: '09171000026',
                                gender: 'Female',
                                age: 29,
                                occupation: 'Entrepreneur',
                            },
                            {
                                passbook: 'PB-0027',
                                sex: 'M',
                                name: 'Carlos Mendoza',
                                membership_date: '2026-03-07',
                                birth_date: '1994-07-13',
                                address: 'Northville, Purok 7, Sample City',
                                tin: '127-227-327-427',
                                phone_number: '09171000027',
                                gender: 'Male',
                                age: 30,
                                occupation: 'Store Owner',
                            },
                            {
                                passbook: 'PB-0028',
                                sex: 'F',
                                name: 'Rose Villanueva',
                                membership_date: '2026-03-08',
                                birth_date: '1995-08-15',
                                address: 'Northville, Purok 8, Sample City',
                                tin: '128-228-328-428',
                                phone_number: '09171000028',
                                gender: 'Female',
                                age: 31,
                                occupation: 'Office Clerk',
                            },
                            {
                                passbook: 'PB-0029',
                                sex: 'M',
                                name: 'Ramon Garcia',
                                membership_date: '2026-03-09',
                                birth_date: '1996-09-17',
                                address: 'Northville, Purok 9, Sample City',
                                tin: '129-229-329-429',
                                phone_number: '09171000029',
                                gender: 'Male',
                                age: 32,
                                occupation: 'Carpenter',
                            },
                            {
                                passbook: 'PB-0030',
                                sex: 'F',
                                name: 'Grace Navarro',
                                membership_date: '2026-03-10',
                                birth_date: '1997-10-19',
                                address: 'Northville, Purok 10, Sample City',
                                tin: '130-230-330-430',
                                phone_number: '09171000030',
                                gender: 'Female',
                                age: 33,
                                occupation: 'Nurse',
                            },
                        ],
                        group_male_total_members: 5,
                        group_female_total_members: 5,
                        group_total_non_male_female: 0,
                        group_by_sub_total_members: 10,
                    },
                ],
                group_total_members: 30,
                group_male_total_members: 15,
                group_female_total_members: 15,
                group_total_non_male_female: 0,
                group_total: 30,
            },
            {
                group_title: 'ASSOCIATE MEMBERS',
                group_by_data_entries: [
                    {
                        group_by_title: 'JANUARY 2026',
                        group_by_data_entries: [
                            {
                                passbook: 'PB-0101',
                                sex: 'M',
                                name: 'Juan Dela Cruz',
                                membership_date: '2026-01-01',
                                birth_date: '1988-01-01',
                                address: 'Lower Valley, Purok 1, Sample City',
                                tin: '201-301-401-501',
                                phone_number: '09171000101',
                                gender: 'Male',
                                age: 24,
                                occupation: 'Farmer',
                            },
                            {
                                passbook: 'PB-0102',
                                sex: 'F',
                                name: 'Maria Santos',
                                membership_date: '2026-01-02',
                                birth_date: '1989-02-03',
                                address: 'Lower Valley, Purok 2, Sample City',
                                tin: '202-302-402-502',
                                phone_number: '09171000102',
                                gender: 'Female',
                                age: 25,
                                occupation: 'Vendor',
                            },
                            {
                                passbook: 'PB-0103',
                                sex: 'M',
                                name: 'Pedro Reyes',
                                membership_date: '2026-01-03',
                                birth_date: '1990-03-05',
                                address: 'Lower Valley, Purok 3, Sample City',
                                tin: '203-303-403-503',
                                phone_number: '09171000103',
                                gender: 'Male',
                                age: 26,
                                occupation: 'Driver',
                            },
                            {
                                passbook: 'PB-0104',
                                sex: 'F',
                                name: 'Liza Ramos',
                                membership_date: '2026-01-04',
                                birth_date: '1991-04-07',
                                address: 'Lower Valley, Purok 4, Sample City',
                                tin: '204-304-404-504',
                                phone_number: '09171000104',
                                gender: 'Female',
                                age: 27,
                                occupation: 'Teacher',
                            },
                            {
                                passbook: 'PB-0105',
                                sex: 'M',
                                name: 'Arman Bautista',
                                membership_date: '2026-01-05',
                                birth_date: '1992-05-09',
                                address: 'Lower Valley, Purok 5, Sample City',
                                tin: '205-305-405-505',
                                phone_number: '09171000105',
                                gender: 'Male',
                                age: 28,
                                occupation: 'Mechanic',
                            },
                            {
                                passbook: 'PB-0106',
                                sex: 'F',
                                name: 'Ana Lopez',
                                membership_date: '2026-01-06',
                                birth_date: '1993-06-11',
                                address: 'Lower Valley, Purok 6, Sample City',
                                tin: '206-306-406-506',
                                phone_number: '09171000106',
                                gender: 'Female',
                                age: 29,
                                occupation: 'Entrepreneur',
                            },
                            {
                                passbook: 'PB-0107',
                                sex: 'M',
                                name: 'Carlos Mendoza',
                                membership_date: '2026-01-07',
                                birth_date: '1994-07-13',
                                address: 'Lower Valley, Purok 7, Sample City',
                                tin: '207-307-407-507',
                                phone_number: '09171000107',
                                gender: 'Male',
                                age: 30,
                                occupation: 'Store Owner',
                            },
                            {
                                passbook: 'PB-0108',
                                sex: 'F',
                                name: 'Rose Villanueva',
                                membership_date: '2026-01-08',
                                birth_date: '1995-08-15',
                                address: 'Lower Valley, Purok 8, Sample City',
                                tin: '208-308-408-508',
                                phone_number: '09171000108',
                                gender: 'Female',
                                age: 31,
                                occupation: 'Office Clerk',
                            },
                            {
                                passbook: 'PB-0109',
                                sex: 'M',
                                name: 'Ramon Garcia',
                                membership_date: '2026-01-09',
                                birth_date: '1996-09-17',
                                address: 'Lower Valley, Purok 9, Sample City',
                                tin: '209-309-409-509',
                                phone_number: '09171000109',
                                gender: 'Male',
                                age: 32,
                                occupation: 'Carpenter',
                            },
                            {
                                passbook: 'PB-0110',
                                sex: 'F',
                                name: 'Grace Navarro',
                                membership_date: '2026-01-10',
                                birth_date: '1997-10-19',
                                address: 'Lower Valley, Purok 10, Sample City',
                                tin: '210-310-410-510',
                                phone_number: '09171000110',
                                gender: 'Female',
                                age: 33,
                                occupation: 'Nurse',
                            },
                        ],
                        group_male_total_members: 5,
                        group_female_total_members: 5,
                        group_total_non_male_female: 0,
                        group_by_sub_total_members: 10,
                    },
                    {
                        group_by_title: 'MARCH 2026',
                        group_by_data_entries: [
                            {
                                passbook: 'PB-0111',
                                sex: 'M',
                                name: 'Juan Dela Cruz',
                                membership_date: '2026-03-01',
                                birth_date: '1988-01-01',
                                address: 'Barangay East, Purok 1, Sample City',
                                tin: '211-311-411-511',
                                phone_number: '09171000111',
                                gender: 'Male',
                                age: 24,
                                occupation: 'Farmer',
                            },
                            {
                                passbook: 'PB-0112',
                                sex: 'F',
                                name: 'Maria Santos',
                                membership_date: '2026-03-02',
                                birth_date: '1989-02-03',
                                address: 'Barangay East, Purok 2, Sample City',
                                tin: '212-312-412-512',
                                phone_number: '09171000112',
                                gender: 'Female',
                                age: 25,
                                occupation: 'Vendor',
                            },
                            {
                                passbook: 'PB-0113',
                                sex: 'M',
                                name: 'Pedro Reyes',
                                membership_date: '2026-03-03',
                                birth_date: '1990-03-05',
                                address: 'Barangay East, Purok 3, Sample City',
                                tin: '213-313-413-513',
                                phone_number: '09171000113',
                                gender: 'Male',
                                age: 26,
                                occupation: 'Driver',
                            },
                            {
                                passbook: 'PB-0114',
                                sex: 'F',
                                name: 'Liza Ramos',
                                membership_date: '2026-03-04',
                                birth_date: '1991-04-07',
                                address: 'Barangay East, Purok 4, Sample City',
                                tin: '214-314-414-514',
                                phone_number: '09171000114',
                                gender: 'Female',
                                age: 27,
                                occupation: 'Teacher',
                            },
                            {
                                passbook: 'PB-0115',
                                sex: 'M',
                                name: 'Arman Bautista',
                                membership_date: '2026-03-05',
                                birth_date: '1992-05-09',
                                address: 'Barangay East, Purok 5, Sample City',
                                tin: '215-315-415-515',
                                phone_number: '09171000115',
                                gender: 'Male',
                                age: 28,
                                occupation: 'Mechanic',
                            },
                            {
                                passbook: 'PB-0116',
                                sex: 'F',
                                name: 'Ana Lopez',
                                membership_date: '2026-03-06',
                                birth_date: '1993-06-11',
                                address: 'Barangay East, Purok 6, Sample City',
                                tin: '216-316-416-516',
                                phone_number: '09171000116',
                                gender: 'Female',
                                age: 29,
                                occupation: 'Entrepreneur',
                            },
                            {
                                passbook: 'PB-0117',
                                sex: 'M',
                                name: 'Carlos Mendoza',
                                membership_date: '2026-03-07',
                                birth_date: '1994-07-13',
                                address: 'Barangay East, Purok 7, Sample City',
                                tin: '217-317-417-517',
                                phone_number: '09171000117',
                                gender: 'Male',
                                age: 30,
                                occupation: 'Store Owner',
                            },
                            {
                                passbook: 'PB-0118',
                                sex: 'F',
                                name: 'Rose Villanueva',
                                membership_date: '2026-03-08',
                                birth_date: '1995-08-15',
                                address: 'Barangay East, Purok 8, Sample City',
                                tin: '218-318-418-518',
                                phone_number: '09171000118',
                                gender: 'Female',
                                age: 31,
                                occupation: 'Office Clerk',
                            },
                            {
                                passbook: 'PB-0119',
                                sex: 'M',
                                name: 'Ramon Garcia',
                                membership_date: '2026-03-09',
                                birth_date: '1996-09-17',
                                address: 'Barangay East, Purok 9, Sample City',
                                tin: '219-319-419-519',
                                phone_number: '09171000119',
                                gender: 'Male',
                                age: 32,
                                occupation: 'Carpenter',
                            },
                            {
                                passbook: 'PB-0120',
                                sex: 'F',
                                name: 'Grace Navarro',
                                membership_date: '2026-03-10',
                                birth_date: '1997-10-19',
                                address: 'Barangay East, Purok 10, Sample City',
                                tin: '220-320-420-520',
                                phone_number: '09171000120',
                                gender: 'Female',
                                age: 33,
                                occupation: 'Nurse',
                            },
                        ],
                        group_male_total_members: 5,
                        group_female_total_members: 5,
                        group_total_non_male_female: 0,
                        group_by_sub_total_members: 10,
                    },
                ],
                group_total_members: 20,
                group_male_total_members: 10,
                group_female_total_members: 10,
                group_total_non_male_female: 0,
                group_total: 20,
            },
        ],

        total_male: 25,
        total_female: 25,
        total_non_male_female: 0,
        total_member: 50,

        density: 'normal',
    }

export const MEMBER_LISTING_REPORT_TEMPLATES: GeneratedReportTemplate<
    IMemberListingReportTemplate,
    { presentation_style: TPresentationStyle }
>[] = [
    {
        id: 'member-listing-identity-bio-t1',
        template_name: 'Identity Bio',
        report_name: 'MemberListingReport',
        template: MEMBER_LISTING_IDENTITY_BIO_T1,
        template_filter: { presentation_style: 'identity_bio' },
        default_unit: 'in',
        width: '13in',
        height: '8.5in',
        density: 'normal',
        orientation: 'portrait',
        preview_data: SHARED_MEMBER_LISTING_PREVIEW_DATA,
    },
    {
        id: 'member-listing-summary-stat-t1',
        template_name: 'Summary Stat',
        report_name: 'MemberListingReport',
        template: MEMBER_LISTING_SUMMARY_STAT_T1,
        template_filter: { presentation_style: 'summary_stat' },
        default_unit: 'in',
        width: '13in',
        height: '8.5in',
        density: 'normal',
        orientation: 'portrait',
        preview_data: SHARED_MEMBER_LISTING_PREVIEW_DATA,
    },
    {
        id: 'member-listing-compliance-tin-t1',
        template_name: 'Compliance TIN',
        report_name: 'MemberListingReport',
        template: MEMBER_LISTING_COMPLIANCE_TIN_T1,
        template_filter: { presentation_style: 'compliance_tin' },
        default_unit: 'in',
        width: '13in',
        height: '8.5in',
        density: 'normal',
        orientation: 'portrait',
        preview_data: SHARED_MEMBER_LISTING_PREVIEW_DATA,
    },
    {
        id: 'member-listing-detailed-loc-t1',
        template_name: 'Detailed Loc',
        report_name: 'MemberListingReport',
        template: MEMBER_LISTING_DETAILED_LOC_T1,
        template_filter: { presentation_style: 'detailed_loc' },
        default_unit: 'in',
        width: '13in',
        height: '8.5in',
        density: 'normal',
        orientation: 'portrait',
        preview_data: SHARED_MEMBER_LISTING_PREVIEW_DATA,
    },
]
