import {
    TbMinus as MinusIcon,
    TbSquareF1 as F1Icon,
    TbSquareF2 as F2Icon,
    TbSquareF3 as F3Icon,
    TbSunMoon as SunMoonIcon,
    TbMoneybag as MoneyBagIcon,
    TbGhost2Filled as GhostIcon,
    TbBlockquote as BlockQuoteIcon,
    TbCreditCard as CreditCardIcon2,
    TbHeartHandshake as HandShakeHeartIcon,
} from 'react-icons/tb'

import {
    CiGlobe as GlobeIcon,
    CiExport as ExportIcon,
    CiBarcode as BarcodeScanIcon,
    CiFilter as FunnelOutlineIcon,
} from 'react-icons/ci'

import {
    GoDotFill as DotBigIcon,
    GoArrowLeft as ArrowLeftIcon,
    GoArrowRight as ArrowRightIcon,
    GoSearch as MagnifyingGlassIcon,
    GoOrganization as OrganizationIcon,
} from 'react-icons/go'

import {
    IoIosClose as XIcon,
    IoIosCog as GearIcon,
    IoIosCode as IoIosCodeIcon,
    IoIosFunnel as FunnelFilledIcon,
} from 'react-icons/io'

import {
    LuCopy as CopyIcon,
    LuView as ViewIcon,
    LuUndo2 as UndoIcon,
    LuRedo2 as RedoIcon,
    LuTrash as TrashIcon,
    LuImage as ImageIcon,
    LuFileX as FileXIcon,
    LuClock8 as ClockIcon,
    LuQrCode as QrCodeIcon,
    LuReplace as ReplaceIcon,
    LuCalendar as CalendarIcon,
    LuScale as WeightScaleIcon,
    LuCameraOff as CameraOffIcon,
    LuListOrdered as ListOrderedIcon,
    LuCalendarCheck as CalendarCheckIcon,
    LuExternalLink as OpenExternalLinkIcon,
    LuChevronsUpDown as ChevronsUpDownIcon,
    LuHardDriveUpload as HardDriveUploadIcon,
} from 'react-icons/lu'

import {
    BsBuildingGear as BuildingCogIcon,
    BsLayoutSidebarInset as SidebarIcon,
    BsLayoutSidebarInsetReverse as SidebarRightIcon,
} from 'react-icons/bs'

import {
    LiaUser as UserIcon,
    LiaUserTagSolid as UserTagIcon,
    LiaUserCogSolid as UserCogIcon,
    LiaShieldAltSolid as ShieldIcon,
    LiaUserClockSolid as UserClockIcon,
    LiaUserShieldSolid as UserShieldIcon,
    LiaMapMarkedAltSolid as MapMarkedIcon,
} from 'react-icons/lia'

import {
    PiPlus as PlusIcon,
    PiEmpty as EmptyIcon,
    PiPushPin as PushPinIcon,
    PiParkDuotone as ParkIcon,
    PiUserList as UserListIcon,
    PiBuilding as BuildingIcon,
    PiNewspaper as ReportsIcon,
    PiUsersThree as Users3Icon,
    PiCodeBlock as CodeBlockIcon,
    PiNotepadDuotone as NoteIcon,
    PiWarningFill as WarningFillIcon,
    PiBankDuotone as BankDuoToneIcon,
    PiPushPinSlash as PushPinSlashIcon,
    PiHandCoinsDuotone as HandCoinsIcon,
    PiMicrosoftExcelLogoFill as ExcelIcon,
    PiHeartBreakFill as HeartBreakFillIcon,
    PiSignatureLight as SignatureLightIcon,
    PiBuildingOffice as BuildingBranchIcon,
    PiHandDepositDuotone as HandDepositIcon,
    PiListBulletsBold as ListBulletsBoldIcon,
    PiGraduationCapFill as GraduationCapIcon,
    PiWarningCircleFill as WarningCircleIcon,
    PiHandWithdrawDuotone as HandWithdrawIcon,
    PiPlugsConnectedFill as PlugConnectFillIcon,
    PiContactlessPaymentDuotone as OnlinePaymentIcon,
    PiTextStrikethroughLight as TextStrikethroughLightIcon,
} from 'react-icons/pi'

import {
    HiOutlineSun as SunIcon,
    HiOutlineMoon as MoonIcon,
    HiFolder as FolderFillIcon,
    HiPencil as PencilFillIcon,
    HiOutlineCog as SettingsIcon,
    HiOutlineCodeBracket as DevIcon,
    HiOutlineArrowUp as ArrowUpIcon,
    HiOutlineBell as NotificationIcon,
    HiChevronDown as ArrowChevronDown,
    HiChevronRight as ArrowChevronRight,
    HiOutlineBriefcase as BriefCaseIcon,
    HiOutlineArrowDown as ArrowDownIcon,
    HiOutlinePencil as PencilOutlineIcon,
    HiOutlineSquaresPlus as DashboardIcon,
    HiAdjustmentsHorizontal as AdjustIcon,
    HiOutlineChevronDown as ChevronDownIcon,
    HiOutlineChevronLeft as ChevronLeftIcon,
    HiOutlineArrowsUpDown as ArrowUpDownIcon,
    HiOutlineChevronRight as ChevronRightIcon,
    HiOutlineQuestionMarkCircle as QuestionIcon,
    HiOutlineChatBubbleOvalLeft as MessagesIcon,
    HiShieldExclamation as ShieldExclamationIcon,
    HiOutlineChevronDoubleLeft as ChevronsLeftIcon,
    HiOutlineArrowRightEndOnRectangle as LogoutIcon,
    HiOutlineChevronDoubleRight as ChevronsRightIcon,
    HiOutlineChatBubbleBottomCenterText as FeedbackIcon,
} from 'react-icons/hi2'

import {
    AiOutlineKey as KeyIcon,
    AiFillHome as HomeFillIcon,
    AiOutlineClear as SmallBrushIcon,
    AiOutlineFullscreen as FullscreenIcon,
    AiOutlineLoading as LoadingCircleIcon,
    AiOutlineMessage as MessageOutlineIcon,
    AiOutlineRotateLeft as RotateBoxLeftIcon,
    AiOutlineRotateRight as RotateBoxRightIcon,
    AiOutlineFullscreenExit as FullscreenExitIcon,
    AiOutlineLoading3Quarters as LoadingSpinnerIcon,
} from 'react-icons/ai'

import {
    MdOutlineDraw as DrawIcon,
    MdOutlineEmail as EmailIcon,
    MdFamilyRestroom as FamilyIcon,
    MdRotateLeft as RotateLeftIcon,
    MdOutlineSavings as SavingsIcon,
    MdAccountBalance as AccountsIcon,
    MdRotateRight as RotateRightIcon,
    MdMarkEmailRead as EmailCheckIcon,
    MdOutlineGroupAdd as UsersAddIcon,
    MdOutlinePayments as PaymentsIcon,
    MdOutlineAccountBalance as BankIcon,
    MdCameraEnhance as CameraSelectIcon,
    MdFlipCameraAndroid as CameraFlipIcon,
    MdManageAccounts as AccountSettingIcon,
    MdOutlineLocalPhone as PhoneOutlineIcon,
    MdOutlineScreenshotMonitor as MonitorIcon,
    MdOutlineQueryStats as FinanceReportsIcon,
    MdOutlineManageAccounts as AccountSetupIcon,
    MdOutlineRotate90DegreesCw as Rotate90DegreeRightIcon,
    MdOutlineRotate90DegreesCcw as Rotate90DegreeLeftIcon,
} from 'react-icons/md'

import {
    BsImage as Image2Icon,
    BsZoomIn as ZoomInIcon,
    BsZoomOut as ZoomOutIcon,
    BsSignpost2Fill as SignPostIcon,
    BsCameraFill as CameraFillIcon,
    BsUiChecksGrid as ChecksGridIcon,
    BsPatchCheck as VerifiedPatchIcon,
    BsFileEarmarkFill as FileFillIcon,
    BsShieldLockFill as ShieldLockIcon,
    BsPatchCheckFill as BadgeCheckIcon,
    BsPatchMinusFill as BadgeMinusIcon,
    BsShieldFillCheck as ShieldCheckIcon,
    BsPatchQuestion as BadgeQuestionIcon,
    BsLayoutSidebarInset as SidebarLeftIcon,
    BsFileEarmarkPdfFill as PDFFileFillIcon,
    BsFileEarmarkTextFill as TextFileFillIcon,
    BsFileEarmarkPlayFill as VideoFileFillIcon,
    BsFillPatchMinusFill as BadgeMinusFillIcon,
    BsFillPatchCheckFill as BadgeCheckFillIcon,
    BsDashSquareDotted as DashSquareDottedIcon,
    BsPatchExclamation as BadgeExclamationIcon,
    BsFileEarmarkMusicFill as MusicFileFillIcon,
    BsFileEarmarkImageFill as ImageFileFillIcon,
    BsFileEarmarkExcelFill as ExcelFileFillIcon,
    BsPatchQuestionFill as BadgeQuestionFillIcon,
    BsFileEarmarkWordFill as DocumentFileFillIcon,
    BsPatchExclamationFill as BadgeExclamationFillIcon,
    BsFileEarmarkSpreadsheetFill as SpreadSheetFileIcon,
    BsFillQuestionCircleFill as QuestionCircleFillIcon,
} from 'react-icons/bs'

import {
    IoLink as LinkIcon,
    IoLayers as LayersIcon,
    IoReload as ReloadIcon,
    IoStorefront as StoreIcon,
    IoLanguage as LanguageIcon,
    IoCloseOutline as CloseIcon,
    IoLocation as PinLocationIcon,
    IoPrintOutline as PrinterIcon,
    IoCallOutline as TelephoneIcon,
    IoCalendar as CalendarDotsIcon,
    IoCheckmarkOutline as CheckIcon,
    IoReceiptOutline as ReceiptIcon,
    IoPencilOutline as EditPencilIcon,
    IoLocationSharp as LocationPinIcon,
    IoFootstepsOutline as FootstepsIcon,
    IoReturnDownBackOutline as BackIcon,
    IoKeySharp as KeySharpIcon,
} from 'react-icons/io5'

import {
    RxReset as ResetIcon,
    RxReload as RefreshIcon,
    RxEyeNone as EyeNoneIcon,
    RxFontItalic as ToolbarItalicIcon,
    RxDotsVertical as DotsVerticalIcon,
    RxDragHandleDots2 as DragHandleIcon,
    RxMixerHorizontal as MixerHorizontalIcon,
} from 'react-icons/rx'

import {
    FaRegMap as MapIcon,
    FaRegEye as EyeIcon,
    FaBold as FaBoldIcon,
    FaFileCsv as CsvIcon,
    FaPhoneAlt as PhoneIcon,
    FaMoneyBill as BillIcon,
    FaTabletAlt as TabletIcon,
    FaBookOpen as BookOpenIcon,
    FaCreditCard as CreditCardIcon,
    FaUserClock as UserClockFillIcon,
    FaCalendarCheck as FaCalendarCheckIcon,
    FaTimesCircle as FaTimesIcon,
} from 'react-icons/fa'

import {
    FaPlay as PlayIcon,
    FaStop as StopIcon,
    FaIdCard as IdCardIcon,
    FaSchool as SchoolIcon,
    FaCheck as CheckFillIcon,
    FaUserPlus as UserPlusIcon,
    FaUserLock as UserLockIcon,
    FaTreeCity as TreeCityIcon,
    FaVenusMars as GendersIcon,
    FaChartPie as PieChartIcon,
    FaMoneyCheck as MoneyCheckIcon,
    FaLandmarkFlag as LandmarkIcon,
    FaAddressCard as AddressCardIcon,
    FaArrowTrendUp as ArrowTrendUpIcon,
    FaBoxesStacked as BoxesStackedIcon,
    FaHouseChimneyWindow as HouseIcon,
    FaBusinessTime as BriefCaseClockIcon,
    FaCircleCheck as FaCheckIcon,
    FaArrowUpLong as ArrowUpLong,
} from 'react-icons/fa6'

import {
    RiListCheck3 as TransactionListIcon,
    RiFlipVerticalFill as FlipVerticalIcon,
    RiFlipVerticalLine as FlipVerticalLineIcon,
    RiFlipHorizontalFill as FlipHorizontalIcon,
    RiFlipHorizontalLine as FlipHorizontalLineIcon,
} from 'react-icons/ri'

import {
    FiHash as HashIcon,
    FiCamera as CameraIcon,
    FiDownload as DownloadIcon,
    FiCodesandbox as CodeSandBox,
    FiNavigation as NavigationIcon,
} from 'react-icons/fi'

import {
    GiWallet as WalletIcon,
    GiVillage as VillageIcon,
    GiTakeMyMoney as MoneyIcon,
    GiTreeBranch as BranchIcon,
    GiWoodenSign as WoodSignsIcon,
    GiMoneyStack as MoneyStackIcon,
    GiMoneyStack as GiMoneyStackIcon,
} from 'react-icons/gi'

import {
    CgFacebook as FacebookIcon,
    CgInternal as InternalIcon,
    CgDetailsLess as DetailsIcon,
    CgSmartphone as SmartphoneIcon,
    CgUnavailable as UnavailableIcon,
} from 'react-icons/cg'

import { RxDotFilled as DotMediumIcon } from 'react-icons/rx'

import {
    GrFormNextLink as NextIcon,
    GrPowerReset as PowerResetIcon,
    GrView as EyeViewIcon,
} from 'react-icons/gr'

import {
    VscError as ErrorIcon,
    VscExclude as ExcludeIcon,
    VscLayersDot as LayersSharpDotIcon,
    VscBracketError as BracketErrorIcon,
    VscCommentDraft as CommentDashedIcon,
    VscLocation as LocationPinOutlineIcon,
} from 'react-icons/vsc'

import { BiErrorCircle as WarningIcon } from 'react-icons/bi'

import { SlOptions as OptionsIcon } from 'react-icons/sl'

import {
    GrMoney as CoinsStackIcon,
    GrVmMaintenance as MaintenanceIcon,
} from 'react-icons/gr'

import { TiBook as BookIcon } from 'react-icons/ti'

export {
    XIcon,
    F1Icon,
    F2Icon,
    F3Icon,
    MapIcon,
    CsvIcon,
    SunIcon,
    KeyIcon,
    DevIcon,
    EyeIcon,
    BookIcon,
    ViewIcon,
    StopIcon,
    PlayIcon,
    NoteIcon,
    CopyIcon,
    BankIcon,
    PlusIcon,
    BillIcon,
    UndoIcon,
    RedoIcon,
    UserIcon,
    MoonIcon,
    DrawIcon,
    ParkIcon,
    LinkIcon,
    GearIcon,
    HashIcon,
    BackIcon,
    NextIcon,
    GlobeIcon,
    GhostIcon,
    MoneyIcon,
    EmptyIcon,
    MinusIcon,
    ErrorIcon,
    FileXIcon,
    TrashIcon,
    ClockIcon,
    CloseIcon,
    EmailIcon,
    ImageIcon,
    CheckIcon,
    PhoneIcon,
    ExcelIcon,
    StoreIcon,
    ResetIcon,
    HouseIcon,
    TabletIcon,
    FamilyIcon,
    ReloadIcon,
    QrCodeIcon,
    DotBigIcon,
    CameraIcon,
    LayersIcon,
    FaBoldIcon,
    ShieldIcon,
    Users3Icon,
    BranchIcon,
    LogoutIcon,
    ExportIcon,
    ZoomInIcon,
    AdjustIcon,
    WalletIcon,
    SchoolIcon,
    Image2Icon,
    IdCardIcon,
    EyeViewIcon,
    CodeSandBox,
    ExcludeIcon,
    ReceiptIcon,
    PrinterIcon,
    SavingsIcon,
    DetailsIcon,
    ReplaceIcon,
    WarningIcon,
    MonitorIcon,
    OptionsIcon,
    UserCogIcon,
    GendersIcon,
    RefreshIcon,
    ArrowUpIcon,
    SidebarIcon,
    SunMoonIcon,
    ZoomOutIcon,
    VillageIcon,
    ReportsIcon,
    PushPinIcon,
    EyeNoneIcon,
    UserTagIcon,
    UserPlusIcon,
    FaCheckIcon,
    FaTimesIcon,
    ArrowUpLong,
    LandmarkIcon,
    SignPostIcon,
    InternalIcon,
    UserLockIcon,
    LanguageIcon,
    BookOpenIcon,
    PieChartIcon,
    AccountsIcon,
    PaymentsIcon,
    HomeFillIcon,
    FacebookIcon,
    QuestionIcon,
    SettingsIcon,
    UserListIcon,
    MessagesIcon,
    FeedbackIcon,
    BuildingIcon,
    DownloadIcon,
    CalendarIcon,
    FileFillIcon,
    UsersAddIcon,
    TreeCityIcon,
    KeySharpIcon,
    MoneyBagIcon,
    CheckFillIcon,
    HandCoinsIcon,
    MapMarkedIcon,
    CodeBlockIcon,
    ArrowLeftIcon,
    BriefCaseIcon,
    ArrowDownIcon,
    CameraOffIcon,
    DotMediumIcon,
    FootstepsIcon,
    UserClockIcon,
    DashboardIcon,
    IoIosCodeIcon,
    WoodSignsIcon,
    TelephoneIcon,
    ChecksGridIcon,
    NavigationIcon,
    ShieldLockIcon,
    MoneyStackIcon,
    MoneyCheckIcon,
    FolderFillIcon,
    ArrowRightIcon,
    CoinsStackIcon,
    SmartphoneIcon,
    PencilFillIcon,
    SmallBrushIcon,
    FullscreenIcon,
    RotateLeftIcon,
    PowerResetIcon,
    BlockQuoteIcon,
    DragHandleIcon,
    CameraFillIcon,
    EditPencilIcon,
    BadgeMinusIcon,
    BadgeCheckIcon,
    EmailCheckIcon,
    CameraFlipIcon,
    CreditCardIcon,
    UserShieldIcon,
    WeightScaleIcon,
    CreditCardIcon2,
    PinLocationIcon,
    UnavailableIcon,
    MaintenanceIcon,
    WarningFillIcon,
    ShieldCheckIcon,
    AddressCardIcon,
    ArrowUpDownIcon,
    ChevronLeftIcon,
    SidebarLeftIcon,
    BuildingCogIcon,
    ListOrderedIcon,
    RotateRightIcon,
    LocationPinIcon,
    HandDepositIcon,
    ChevronDownIcon,
    PDFFileFillIcon,
    BankDuoToneIcon,
    BarcodeScanIcon,
    OrganizationIcon,
    CalendarDotsIcon,
    BracketErrorIcon,
    ArrowTrendUpIcon,
    BoxesStackedIcon,
    NotificationIcon,
    ChevronsLeftIcon,
    TextFileFillIcon,
    PhoneOutlineIcon,
    FlipVerticalIcon,
    FunnelFilledIcon,
    PushPinSlashIcon,
    DotsVerticalIcon,
    ChevronRightIcon,
    CameraSelectIcon,
    SidebarRightIcon,
    HandWithdrawIcon,
    ArrowChevronDown,
    GiMoneyStackIcon,
    AccountSetupIcon,
    BadgeQuestionIcon,
    VideoFileFillIcon,
    MusicFileFillIcon,
    ImageFileFillIcon,
    ExcelFileFillIcon,
    GraduationCapIcon,
    RotateBoxLeftIcon,
    ToolbarItalicIcon,
    ChevronsRightIcon,
    FunnelOutlineIcon,
    CalendarCheckIcon,
    WarningCircleIcon,
    VerifiedPatchIcon,
    OnlinePaymentIcon,
    LoadingCircleIcon,
    PencilOutlineIcon,
    UserClockFillIcon,
    CommentDashedIcon,
    ArrowChevronRight,
    FinanceReportsIcon,
    LayersSharpDotIcon,
    SignatureLightIcon,
    HandShakeHeartIcon,
    FlipHorizontalIcon,
    RotateBoxRightIcon,
    BadgeCheckFillIcon,
    BadgeMinusFillIcon,
    BuildingBranchIcon,
    LoadingSpinnerIcon,
    ChevronsUpDownIcon,
    AccountSettingIcon,
    FullscreenExitIcon,
    MessageOutlineIcon,
    HeartBreakFillIcon,
    BriefCaseClockIcon,
    PlugConnectFillIcon,
    FaCalendarCheckIcon,
    MagnifyingGlassIcon,
    SpreadSheetFileIcon,
    HardDriveUploadIcon,
    ListBulletsBoldIcon,
    MixerHorizontalIcon,
    TransactionListIcon,
    DashSquareDottedIcon,
    OpenExternalLinkIcon,
    FlipVerticalLineIcon,
    BadgeExclamationIcon,
    DocumentFileFillIcon,
    ShieldExclamationIcon,
    BadgeQuestionFillIcon,
    LocationPinOutlineIcon,
    QuestionCircleFillIcon,
    FlipHorizontalLineIcon,
    Rotate90DegreeLeftIcon,
    Rotate90DegreeRightIcon,
    BadgeExclamationFillIcon,
    TextStrikethroughLightIcon,
}
