import { TIcon } from '@/types/components/icon'
import {
    AiOutlineFullscreenExit as FullscreenExitIcon,
    AiOutlineFullscreen as FullscreenIcon,
    AiFillHome as HomeFillIcon,
    AiOutlineKey as KeyIcon,
    AiOutlineLoading as LoadingCircleIcon,
    AiOutlineLoading3Quarters as LoadingSpinnerIcon,
    AiOutlineMessage as MessageOutlineIcon,
    AiOutlineRotateLeft as RotateBoxLeftIcon,
    AiOutlineRotateRight as RotateBoxRightIcon,
    AiOutlineClear as SmallBrushIcon,
} from 'react-icons/ai'
import { BiErrorCircle as WarningIcon } from 'react-icons/bi'
import {
    BsRocketTakeoff as BsRocketTakeoffIcon,
    BsBuildingGear as BuildingCogIcon,
    BsLayoutSidebarInset as SidebarIcon,
    BsLayoutSidebarInsetReverse as SidebarRightIcon,
} from 'react-icons/bs'
import {
    BsFillPatchCheckFill as BadgeCheckFillIcon,
    BsPatchCheckFill as BadgeCheckIcon,
    BsPatchExclamationFill as BadgeExclamationFillIcon,
    BsPatchExclamation as BadgeExclamationIcon,
    BsFillPatchMinusFill as BadgeMinusFillIcon,
    BsPatchMinusFill as BadgeMinusIcon,
    BsPatchQuestionFill as BadgeQuestionFillIcon,
    BsPatchQuestion as BadgeQuestionIcon,
    BsCameraFill as CameraFillIcon,
    BsUiChecksGrid as ChecksGridIcon,
    BsDashSquareDotted as DashSquareDottedIcon,
    BsFileEarmarkWordFill as DocumentFileFillIcon,
    BsFileEarmarkExcelFill as ExcelFileFillIcon,
    BsFileEarmarkFill as FileFillIcon,
    BsImage as Image2Icon,
    BsFileEarmarkImageFill as ImageFileFillIcon,
    BsFileEarmarkMusicFill as MusicFileFillIcon,
    BsFileEarmarkPdfFill as PDFFileFillIcon,
    BsFillQuestionCircleFill as QuestionCircleFillIcon,
    BsShieldFillCheck as ShieldCheckIcon,
    BsShieldLockFill as ShieldLockIcon,
    BsLayoutSidebarInset as SidebarLeftIcon,
    BsSignpost2Fill as SignPostIcon,
    BsFileEarmarkSpreadsheetFill as SpreadSheetFileIcon,
    BsFileEarmarkTextFill as TextFileFillIcon,
    BsPatchCheck as VerifiedPatchIcon,
    BsFileEarmarkPlayFill as VideoFileFillIcon,
    BsZoomIn as ZoomInIcon,
    BsZoomOut as ZoomOutIcon,
} from 'react-icons/bs'
import {
    CgDetailsLess as DetailsIcon,
    CgFacebook as FacebookIcon,
    CgInternal as InternalIcon,
    CgSmartphone as SmartphoneIcon,
    CgUnavailable as UnavailableIcon,
} from 'react-icons/cg'
import {
    CiBarcode as BarcodeScanIcon,
    CiExport as ExportIcon,
    CiFilter as FunnelOutlineIcon,
    CiGlobe as GlobeIcon,
} from 'react-icons/ci'
import {
    FaMoneyBill as BillIcon,
    FaBookOpen as BookOpenIcon,
    FaCreditCard as CreditCardIcon,
    FaFileCsv as CsvIcon,
    FaRegEye as EyeIcon,
    FaBold as FaBoldIcon,
    FaCalendarCheck as FaCalendarCheckIcon,
    FaTimesCircle as FaTimesIcon,
    FaRegMap as MapIcon,
    FaMoneyCheckAlt as MoneyCheck2Icon,
    FaPhoneAlt as PhoneIcon,
    FaTabletAlt as TabletIcon,
    FaUserClock as UserClockFillIcon,
} from 'react-icons/fa'
import {
    FaAddressCard as AddressCardIcon,
    FaArrowTrendUp as ArrowTrendUpIcon,
    FaArrowUpLong as ArrowUpLong,
    FaBoxesStacked as BoxesStackedIcon,
    FaBusinessTime as BriefCaseClockIcon,
    FaCheck as CheckFillIcon,
    FaCircleCheck as FaCheckIcon,
    FaVenusMars as GendersIcon,
    FaHouseChimneyWindow as HouseIcon,
    FaIdCard as IdCardIcon,
    FaLandmarkFlag as LandmarkIcon,
    FaMoneyCheck as MoneyCheckIcon,
    FaChartPie as PieChartIcon,
    FaPlay as PlayIcon,
    FaSchool as SchoolIcon,
    FaStop as StopIcon,
    FaTreeCity as TreeCityIcon,
    FaUserLock as UserLockIcon,
    FaUserPlus as UserPlusIcon,
} from 'react-icons/fa6'
import {
    FiCamera as CameraIcon,
    FiCodesandbox as CodeSandBox,
    FiDownload as DownloadIcon,
    FiHash as HashIcon,
    FiNavigation as NavigationIcon,
} from 'react-icons/fi'
import {
    GiTreeBranch as BranchIcon,
    GiMoneyStack as GiMoneyStackIcon,
    GiTakeMyMoney as MoneyIcon,
    GiMoneyStack as MoneyStackIcon,
    GiVillage as VillageIcon,
    GiWallet as WalletIcon,
    GiWoodenSign as WoodSignsIcon,
} from 'react-icons/gi'
import {
    GoArrowLeft as ArrowLeftIcon,
    GoArrowRight as ArrowRightIcon,
    GoDotFill as DotBigIcon,
    GoKebabHorizontal as DotsHorizontalIcon,
    GoSearch as MagnifyingGlassIcon,
    GoOrganization as OrganizationIcon,
} from 'react-icons/go'
import {
    GrView as EyeViewIcon,
    GrFormNextLink as NextIcon,
    GrPowerReset as PowerResetIcon,
} from 'react-icons/gr'
import {
    GrMoney as CoinsStackIcon,
    GrVmMaintenance as MaintenanceIcon,
} from 'react-icons/gr'
import {
    HiAdjustmentsHorizontal as AdjustIcon,
    HiChevronDown as ArrowChevronDown,
    HiChevronRight as ArrowChevronRight,
    HiOutlineArrowDown as ArrowDownIcon,
    HiOutlineArrowsUpDown as ArrowUpDownIcon,
    HiOutlineArrowUp as ArrowUpIcon,
    HiOutlineBriefcase as BriefCaseIcon,
    HiOutlineChevronDown as ChevronDownIcon,
    HiOutlineChevronLeft as ChevronLeftIcon,
    HiOutlineChevronRight as ChevronRightIcon,
    HiOutlineChevronDoubleLeft as ChevronsLeftIcon,
    HiOutlineChevronDoubleRight as ChevronsRightIcon,
    HiOutlineSquaresPlus as DashboardIcon,
    HiOutlineCodeBracket as DevIcon,
    HiOutlineChatBubbleBottomCenterText as FeedbackIcon,
    HiFolder as FolderFillIcon,
    HiOutlineArrowRightEndOnRectangle as LogoutIcon,
    HiOutlineChatBubbleOvalLeft as MessagesIcon,
    HiOutlineMoon as MoonIcon,
    HiOutlineBell as NotificationIcon,
    HiPencil as PencilFillIcon,
    HiOutlinePencil as PencilOutlineIcon,
    HiOutlineQuestionMarkCircle as QuestionIcon,
    HiOutlineCog as SettingsIcon,
    HiShieldExclamation as ShieldExclamationIcon,
    HiOutlineSun as SunIcon,
} from 'react-icons/hi2'
import {
    IoIosFunnel as FunnelFilledIcon,
    IoIosCog as GearIcon,
    IoIosCode as IoIosCodeIcon,
    IoIosClose as XIcon,
} from 'react-icons/io'
import {
    IoReturnDownBackOutline as BackIcon,
    IoCalendar as CalendarDotsIcon,
    IoCheckmarkOutline as CheckIcon,
    IoCloseOutline as CloseIcon,
    IoPencilOutline as EditPencilIcon,
    IoFootstepsOutline as FootstepsIcon,
    IoKeySharp as KeySharpIcon,
    IoLanguage as LanguageIcon,
    IoLayers as LayersIcon,
    IoLink as LinkIcon,
    IoLocationSharp as LocationPinIcon,
    IoLocation as PinLocationIcon,
    IoPricetag as PriceTagIcon,
    IoPrintOutline as PrinterIcon,
    IoReceiptOutline as ReceiptIcon,
    IoReload as ReloadIcon,
    IoStorefront as StoreIcon,
    IoCallOutline as TelephoneIcon,
} from 'react-icons/io5'
import {
    LiaMapMarkedAltSolid as MapMarkedIcon,
    LiaShieldAltSolid as ShieldIcon,
    LiaUserClockSolid as UserClockIcon,
    LiaUserCogSolid as UserCogIcon,
    LiaUser as UserIcon,
    LiaUserShieldSolid as UserShieldIcon,
    LiaUserTagSolid as UserTagIcon,
} from 'react-icons/lia'
import { IconBaseProps, IconType } from 'react-icons/lib'
import {
    LuCalendarCheck as CalendarCheckIcon,
    LuCalendar as CalendarIcon,
    LuCameraOff as CameraOffIcon,
    LuChevronsUpDown as ChevronsUpDownIcon,
    LuClock8 as ClockIcon,
    LuCopy as CopyIcon,
    LuFileX as FileXIcon,
    LuHardDriveUpload as HardDriveUploadIcon,
    LuImage as ImageIcon,
    LuListOrdered as ListOrderedIcon,
    LuExternalLink as OpenExternalLinkIcon,
    LuQrCode as QrCodeIcon,
    LuRedo2 as RedoIcon,
    LuReplace as ReplaceIcon,
    LuTrash as TrashIcon,
    LuUndo2 as UndoIcon,
    LuView as ViewIcon,
    LuScale as WeightScaleIcon,
} from 'react-icons/lu'
import {
    MdManageAccounts as AccountSettingIcon,
    MdOutlineManageAccounts as AccountSetupIcon,
    MdAccountBalance as AccountsIcon,
    MdOutlineAccountBalance as BankIcon,
    MdFlipCameraAndroid as CameraFlipIcon,
    MdCameraEnhance as CameraSelectIcon,
    MdOutlineDraw as DrawIcon,
    MdMarkEmailRead as EmailCheckIcon,
    MdOutlineEmail as EmailIcon,
    MdFamilyRestroom as FamilyIcon,
    MdOutlineQueryStats as FinanceReportsIcon,
    MdOutlineScreenshotMonitor as MonitorIcon,
    MdOutlinePayments as PaymentsIcon,
    MdOutlineLocalPhone as PhoneOutlineIcon,
    MdOutlineRotate90DegreesCcw as Rotate90DegreeLeftIcon,
    MdOutlineRotate90DegreesCw as Rotate90DegreeRightIcon,
    MdRotateLeft as RotateLeftIcon,
    MdRotateRight as RotateRightIcon,
    MdOutlineSavings as SavingsIcon,
    MdGroups as UserGroupIcon,
    MdOutlineGroupAdd as UsersAddIcon,
} from 'react-icons/md'
import {
    PiBankDuotone as BankDuoToneIcon,
    PiBuildingOffice as BuildingBranchIcon,
    PiBuilding as BuildingIcon,
    PiCodeBlock as CodeBlockIcon,
    PiEmpty as EmptyIcon,
    PiMicrosoftExcelLogoFill as ExcelIcon,
    PiGraduationCapFill as GraduationCapIcon,
    PiHandCoinsDuotone as HandCoinsIcon,
    PiHandDepositDuotone as HandDepositIcon,
    PiHandWithdrawDuotone as HandWithdrawIcon,
    PiHeartBreakFill as HeartBreakFillIcon,
    PiListBulletsBold as ListBulletsBoldIcon,
    PiNotepadDuotone as NoteIcon,
    PiContactlessPaymentDuotone as OnlinePaymentIcon,
    PiParkDuotone as ParkIcon,
    PiPlugsConnectedFill as PlugConnectFillIcon,
    PiPlus as PlusIcon,
    PiPushPin as PushPinIcon,
    PiPushPinSlash as PushPinSlashIcon,
    PiNewspaper as ReportsIcon,
    PiSignatureLight as SignatureLightIcon,
    PiTextStrikethroughLight as TextStrikethroughLightIcon,
    PiUserList as UserListIcon,
    PiUsersThree as Users3Icon,
    PiWarningCircleFill as WarningCircleIcon,
    PiWarningFill as WarningFillIcon,
} from 'react-icons/pi'
import {
    RiFlipHorizontalFill as FlipHorizontalIcon,
    RiFlipHorizontalLine as FlipHorizontalLineIcon,
    RiFlipVerticalFill as FlipVerticalIcon,
    RiFlipVerticalLine as FlipVerticalLineIcon,
    RiListCheck3 as TransactionListIcon,
} from 'react-icons/ri'
import {
    RxDotsVertical as DotsVerticalIcon,
    RxDragHandleDots2 as DragHandleIcon,
    RxEyeNone as EyeNoneIcon,
    RxMixerHorizontal as MixerHorizontalIcon,
    RxReload as RefreshIcon,
    RxReset as ResetIcon,
    RxFontItalic as ToolbarItalicIcon,
} from 'react-icons/rx'
import { RxDotFilled as DotMediumIcon } from 'react-icons/rx'
import { SiGitbook as SigiBookIcon } from 'react-icons/si'
import { SlOptions as OptionsIcon } from 'react-icons/sl'
import {
    TbBlockquote as BlockQuoteIcon,
    TbCreditCard as CreditCardIcon2,
    TbSquareF1 as F1Icon,
    TbSquareF2 as F2Icon,
    TbSquareF3 as F3Icon,
    TbGhost2Filled as GhostIcon,
    TbHeartHandshake as HandShakeHeartIcon,
    TbMinus as MinusIcon,
    TbMoneybag as MoneyBagIcon,
    TbSunMoon as SunMoonIcon,
    TbTargetArrow as TargetArrowIcon,
    TbTransactionDollar as TransactionDollarIcon,
    TbUnlink as UnlinkIcon,
} from 'react-icons/tb'
import { TiBook as BookIcon } from 'react-icons/ti'
import {
    VscBracketError as BracketErrorIcon,
    VscCommentDraft as CommentDashedIcon,
    VscError as ErrorIcon,
    VscExclude as ExcludeIcon,
    VscLayersDot as LayersSharpDotIcon,
    VscLocation as LocationPinOutlineIcon,
} from 'react-icons/vsc'

export {
    XIcon,
    F1Icon,
    F2Icon,
    F3Icon,
    MapIcon,
    CsvIcon,
    SunIcon,
    KeyIcon,
    DevIcon,
    EyeIcon,
    BookIcon,
    ViewIcon,
    StopIcon,
    PlayIcon,
    NoteIcon,
    CopyIcon,
    BankIcon,
    PlusIcon,
    BillIcon,
    UndoIcon,
    RedoIcon,
    UserIcon,
    MoonIcon,
    DrawIcon,
    ParkIcon,
    LinkIcon,
    GearIcon,
    HashIcon,
    BackIcon,
    NextIcon,
    GlobeIcon,
    GhostIcon,
    MoneyIcon,
    EmptyIcon,
    MinusIcon,
    ErrorIcon,
    FileXIcon,
    TrashIcon,
    ClockIcon,
    CloseIcon,
    EmailIcon,
    ImageIcon,
    CheckIcon,
    PhoneIcon,
    ExcelIcon,
    StoreIcon,
    ResetIcon,
    HouseIcon,
    TabletIcon,
    UnlinkIcon,
    FamilyIcon,
    ReloadIcon,
    QrCodeIcon,
    DotBigIcon,
    CameraIcon,
    LayersIcon,
    FaBoldIcon,
    ShieldIcon,
    Users3Icon,
    BranchIcon,
    LogoutIcon,
    ExportIcon,
    ZoomInIcon,
    AdjustIcon,
    WalletIcon,
    SchoolIcon,
    Image2Icon,
    IdCardIcon,
    EyeViewIcon,
    CodeSandBox,
    ExcludeIcon,
    ReceiptIcon,
    PrinterIcon,
    SavingsIcon,
    DetailsIcon,
    ReplaceIcon,
    WarningIcon,
    MonitorIcon,
    OptionsIcon,
    UserCogIcon,
    GendersIcon,
    RefreshIcon,
    ArrowUpIcon,
    SidebarIcon,
    SunMoonIcon,
    ZoomOutIcon,
    VillageIcon,
    ReportsIcon,
    PushPinIcon,
    EyeNoneIcon,
    UserTagIcon,
    UserPlusIcon,
    FaCheckIcon,
    FaTimesIcon,
    ArrowUpLong,
    LandmarkIcon,
    SignPostIcon,
    InternalIcon,
    UserLockIcon,
    LanguageIcon,
    BookOpenIcon,
    PriceTagIcon,
    PieChartIcon,
    AccountsIcon,
    PaymentsIcon,
    HomeFillIcon,
    FacebookIcon,
    QuestionIcon,
    SettingsIcon,
    UserListIcon,
    MessagesIcon,
    FeedbackIcon,
    BuildingIcon,
    DownloadIcon,
    CalendarIcon,
    FileFillIcon,
    UsersAddIcon,
    TreeCityIcon,
    KeySharpIcon,
    MoneyBagIcon,
    SigiBookIcon,
    CheckFillIcon,
    HandCoinsIcon,
    MapMarkedIcon,
    CodeBlockIcon,
    ArrowLeftIcon,
    BriefCaseIcon,
    ArrowDownIcon,
    CameraOffIcon,
    DotMediumIcon,
    FootstepsIcon,
    UserClockIcon,
    DashboardIcon,
    IoIosCodeIcon,
    WoodSignsIcon,
    TelephoneIcon,
    UserGroupIcon,
    ChecksGridIcon,
    NavigationIcon,
    ShieldLockIcon,
    MoneyStackIcon,
    MoneyCheckIcon,
    FolderFillIcon,
    ArrowRightIcon,
    CoinsStackIcon,
    SmartphoneIcon,
    PencilFillIcon,
    SmallBrushIcon,
    FullscreenIcon,
    RotateLeftIcon,
    PowerResetIcon,
    BlockQuoteIcon,
    DragHandleIcon,
    CameraFillIcon,
    EditPencilIcon,
    BadgeMinusIcon,
    BadgeCheckIcon,
    EmailCheckIcon,
    CameraFlipIcon,
    CreditCardIcon,
    UserShieldIcon,
    WeightScaleIcon,
    TargetArrowIcon,
    MoneyCheck2Icon,
    CreditCardIcon2,
    PinLocationIcon,
    UnavailableIcon,
    MaintenanceIcon,
    WarningFillIcon,
    ShieldCheckIcon,
    AddressCardIcon,
    ArrowUpDownIcon,
    ChevronLeftIcon,
    SidebarLeftIcon,
    BuildingCogIcon,
    ListOrderedIcon,
    RotateRightIcon,
    LocationPinIcon,
    HandDepositIcon,
    ChevronDownIcon,
    PDFFileFillIcon,
    BankDuoToneIcon,
    BarcodeScanIcon,
    OrganizationIcon,
    CalendarDotsIcon,
    BracketErrorIcon,
    ArrowTrendUpIcon,
    BoxesStackedIcon,
    NotificationIcon,
    ChevronsLeftIcon,
    TextFileFillIcon,
    PhoneOutlineIcon,
    FlipVerticalIcon,
    FunnelFilledIcon,
    PushPinSlashIcon,
    DotsVerticalIcon,
    ChevronRightIcon,
    CameraSelectIcon,
    SidebarRightIcon,
    HandWithdrawIcon,
    ArrowChevronDown,
    GiMoneyStackIcon,
    AccountSetupIcon,
    BadgeQuestionIcon,
    VideoFileFillIcon,
    MusicFileFillIcon,
    ImageFileFillIcon,
    ExcelFileFillIcon,
    GraduationCapIcon,
    RotateBoxLeftIcon,
    ToolbarItalicIcon,
    ChevronsRightIcon,
    FunnelOutlineIcon,
    CalendarCheckIcon,
    WarningCircleIcon,
    VerifiedPatchIcon,
    OnlinePaymentIcon,
    LoadingCircleIcon,
    PencilOutlineIcon,
    UserClockFillIcon,
    CommentDashedIcon,
    ArrowChevronRight,
    DotsHorizontalIcon,
    FinanceReportsIcon,
    LayersSharpDotIcon,
    SignatureLightIcon,
    HandShakeHeartIcon,
    FlipHorizontalIcon,
    RotateBoxRightIcon,
    BadgeCheckFillIcon,
    BadgeMinusFillIcon,
    BuildingBranchIcon,
    LoadingSpinnerIcon,
    ChevronsUpDownIcon,
    AccountSettingIcon,
    FullscreenExitIcon,
    MessageOutlineIcon,
    HeartBreakFillIcon,
    BriefCaseClockIcon,
    BsRocketTakeoffIcon,
    PlugConnectFillIcon,
    FaCalendarCheckIcon,
    MagnifyingGlassIcon,
    SpreadSheetFileIcon,
    HardDriveUploadIcon,
    ListBulletsBoldIcon,
    MixerHorizontalIcon,
    TransactionListIcon,
    DashSquareDottedIcon,
    OpenExternalLinkIcon,
    FlipVerticalLineIcon,
    BadgeExclamationIcon,
    DocumentFileFillIcon,
    ShieldExclamationIcon,
    BadgeQuestionFillIcon,
    TransactionDollarIcon,
    LocationPinOutlineIcon,
    QuestionCircleFillIcon,
    FlipHorizontalLineIcon,
    Rotate90DegreeLeftIcon,
    Rotate90DegreeRightIcon,
    BadgeExclamationFillIcon,
    TextStrikethroughLightIcon,
}

export const IconMap: Record<TIcon, IconType> = {
    X: XIcon,
    F1: F1Icon,
    F2: F2Icon,
    F3: F3Icon,
    Map: MapIcon,
    CSV: CsvIcon,
    Sun: SunIcon,
    Key: KeyIcon,
    Dev: DevIcon,
    Eye: EyeIcon,
    Book: BookIcon,
    View: ViewIcon,
    Stop: StopIcon,
    Play: PlayIcon,
    Note: NoteIcon,
    Copy: CopyIcon,
    Bank: BankIcon,
    Plus: PlusIcon,
    Bill: BillIcon,
    Undo: UndoIcon,
    Redo: RedoIcon,
    User: UserIcon,
    Moon: MoonIcon,
    Draw: DrawIcon,
    Park: ParkIcon,
    Link: LinkIcon,
    Gear: GearIcon,
    Hash: HashIcon,
    Back: BackIcon,
    Next: NextIcon,
    Globe: GlobeIcon,
    Ghost: GhostIcon,
    Money: MoneyIcon,
    Empty: EmptyIcon,
    Minus: MinusIcon,
    Error: ErrorIcon,
    'File X': FileXIcon,
    Trash: TrashIcon,
    Clock: ClockIcon,
    Close: CloseIcon,
    Email: EmailIcon,
    Image: ImageIcon,
    Check: CheckIcon,
    Phone: PhoneIcon,
    Excel: ExcelIcon,
    Store: StoreIcon,
    Reset: ResetIcon,
    House: HouseIcon,
    Tablet: TabletIcon,
    Unlink: UnlinkIcon,
    Family: FamilyIcon,
    Reload: ReloadIcon,
    'QR Code': QrCodeIcon,
    'Dot Big': DotBigIcon,
    Camera: CameraIcon,
    Layers: LayersIcon,
    'FA Bold': FaBoldIcon,
    Shield: ShieldIcon,
    'Users 3': Users3Icon,
    Branch: BranchIcon,
    Logout: LogoutIcon,
    Export: ExportIcon,
    'Zoom In': ZoomInIcon,
    Adjust: AdjustIcon,
    Wallet: WalletIcon,
    School: SchoolIcon,
    'Image 2': Image2Icon,
    'ID Card': IdCardIcon,
    'Eye View': EyeViewIcon,
    'Code SandBox': CodeSandBox,
    Exclude: ExcludeIcon,
    Receipt: ReceiptIcon,
    Printer: PrinterIcon,
    Savings: SavingsIcon,
    Details: DetailsIcon,
    Replace: ReplaceIcon,
    Warning: WarningIcon,
    Monitor: MonitorIcon,
    Options: OptionsIcon,
    'User Cog': UserCogIcon,
    Genders: GendersIcon,
    Refresh: RefreshIcon,
    'Arrow Up': ArrowUpIcon,
    Sidebar: SidebarIcon,
    'Sun Moon': SunMoonIcon,
    'Zoom Out': ZoomOutIcon,
    Village: VillageIcon,
    Reports: ReportsIcon,
    'Push Pin': PushPinIcon,
    'Eye None': EyeNoneIcon,
    'User Tag': UserTagIcon,
    'User Plus': UserPlusIcon,
    'FA Check': FaCheckIcon,
    'FA Times': FaTimesIcon,
    'Arrow Up Long': ArrowUpLong,
    Landmark: LandmarkIcon,
    'Sign Post': SignPostIcon,
    Internal: InternalIcon,
    'User Lock': UserLockIcon,
    Language: LanguageIcon,
    'Book Open': BookOpenIcon,
    'Price Tag': PriceTagIcon,
    'Pie Chart': PieChartIcon,
    Accounts: AccountsIcon,
    Payments: PaymentsIcon,
    'Home Fill': HomeFillIcon,
    Facebook: FacebookIcon,
    Question: QuestionIcon,
    Settings: SettingsIcon,
    'User List': UserListIcon,
    Messages: MessagesIcon,
    Feedback: FeedbackIcon,
    Building: BuildingIcon,
    Download: DownloadIcon,
    Calendar: CalendarIcon,
    'File Fill': FileFillIcon,
    'Users Add': UsersAddIcon,
    'Tree City': TreeCityIcon,
    'Key Sharp': KeySharpIcon,
    'Money Bag': MoneyBagIcon,
    'Check Fill': CheckFillIcon,
    'Hand Coins': HandCoinsIcon,
    'Map Marked': MapMarkedIcon,
    'Code Block': CodeBlockIcon,
    'Arrow Left': ArrowLeftIcon,
    'Brief Case': BriefCaseIcon,
    'Arrow Down': ArrowDownIcon,
    'Camera Off': CameraOffIcon,
    'Dot Medium': DotMediumIcon,
    Footsteps: FootstepsIcon,
    'User Clock': UserClockIcon,
    Dashboard: DashboardIcon,
    IoIosCode: IoIosCodeIcon,
    'Wood Signs': WoodSignsIcon,
    Telephone: TelephoneIcon,
    'User Group': UserGroupIcon,
    'Checks Grid': ChecksGridIcon,
    Navigation: NavigationIcon,
    'Shield Lock': ShieldLockIcon,
    'Money Stack': MoneyStackIcon,
    'Money Check': MoneyCheckIcon,
    'Folder Fill': FolderFillIcon,
    'Arrow Right': ArrowRightIcon,
    'Coins Stack': CoinsStackIcon,
    Smartphone: SmartphoneIcon,
    'Pencil Fill': PencilFillIcon,
    'Small Brush': SmallBrushIcon,
    Fullscreen: FullscreenIcon,
    'Rotate Left': RotateLeftIcon,
    'Power Reset': PowerResetIcon,
    'Block Quote': BlockQuoteIcon,
    'Drag Handle': DragHandleIcon,
    'Camera Fill': CameraFillIcon,
    'Edit Pencil': EditPencilIcon,
    'Badge Minus': BadgeMinusIcon,
    'Badge Check': BadgeCheckIcon,
    'Email Check': EmailCheckIcon,
    'Camera Flip': CameraFlipIcon,
    'Credit Card': CreditCardIcon,
    'User Shield': UserShieldIcon,
    'Weight Scale': WeightScaleIcon,
    'Target Arrow': TargetArrowIcon,
    'Money Check 2': MoneyCheck2Icon,
    'Credit Card 2': CreditCardIcon2,
    'Pin Location': PinLocationIcon,
    Unavailable: UnavailableIcon,
    Maintenance: MaintenanceIcon,
    'Warning Fill': WarningFillIcon,
    'Shield Check': ShieldCheckIcon,
    'Address Card': AddressCardIcon,
    'Arrow Up Down': ArrowUpDownIcon,
    'Chevron Left': ChevronLeftIcon,
    'Sidebar Left': SidebarLeftIcon,
    'Building Cog': BuildingCogIcon,
    'List Ordered': ListOrderedIcon,
    'Rotate Right': RotateRightIcon,
    'Location Pin': LocationPinIcon,
    'Hand Deposit': HandDepositIcon,
    'Chevron Down': ChevronDownIcon,
    'PDF File Fill': PDFFileFillIcon,
    'Bank DuoTone': BankDuoToneIcon,
    'Barcode Scan': BarcodeScanIcon,
    Organization: OrganizationIcon,
    'Calendar Dots': CalendarDotsIcon,
    'Bracket Error': BracketErrorIcon,
    'Arrow Trend Up': ArrowTrendUpIcon,
    'Boxes Stacked': BoxesStackedIcon,
    Notification: NotificationIcon,
    'Chevrons Left': ChevronsLeftIcon,
    'Text File Fill': TextFileFillIcon,
    'Phone Outline': PhoneOutlineIcon,
    'Flip Vertical': FlipVerticalIcon,
    'Funnel Filled': FunnelFilledIcon,
    'Push Pin Slash': PushPinSlashIcon,
    'Dots Vertical': DotsVerticalIcon,
    'Chevron Right': ChevronRightIcon,
    'Camera Select': CameraSelectIcon,
    'Sidebar Right': SidebarRightIcon,
    'Hand Withdraw': HandWithdrawIcon,
    'Arrow Chevron Down': ArrowChevronDown,
    'GiMoney Stack': GiMoneyStackIcon,
    'Account Setup': AccountSetupIcon,
    'Badge Question': BadgeQuestionIcon,
    'Video File Fill': VideoFileFillIcon,
    'Music File Fill': MusicFileFillIcon,
    'Image File Fill': ImageFileFillIcon,
    'Excel File Fill': ExcelFileFillIcon,
    'Graduation Cap': GraduationCapIcon,
    'Rotate Box Left': RotateBoxLeftIcon,
    'Toolbar Italic': ToolbarItalicIcon,
    'Chevrons Right': ChevronsRightIcon,
    'Funnel Outline': FunnelOutlineIcon,
    'Calendar Check': CalendarCheckIcon,
    'Warning Circle': WarningCircleIcon,
    'Verified Patch': VerifiedPatchIcon,
    'Online Payment': OnlinePaymentIcon,
    'Loading Circle': LoadingCircleIcon,
    'Pencil Outline': PencilOutlineIcon,
    'User Clock Fill': UserClockFillIcon,
    'Comment Dashed': CommentDashedIcon,
    'Arrow Chevron Right': ArrowChevronRight,
    'Finance Reports': FinanceReportsIcon,
    'Layers Sharp Dot': LayersSharpDotIcon,
    'Signature Light': SignatureLightIcon,
    'Hand Shake Heart': HandShakeHeartIcon,
    'Flip Horizontal': FlipHorizontalIcon,
    'Rotate Box Right': RotateBoxRightIcon,
    'Badge Check Fill': BadgeCheckFillIcon,
    'Badge Minus Fill': BadgeMinusFillIcon,
    'Building Branch': BuildingBranchIcon,
    'Loading Spinner': LoadingSpinnerIcon,
    'Chevrons Up Down': ChevronsUpDownIcon,
    'Account Setting': AccountSettingIcon,
    'Fullscreen Exit': FullscreenExitIcon,
    'Message Outline': MessageOutlineIcon,
    'Heart Break Fill': HeartBreakFillIcon,
    'Brief Case Clock': BriefCaseClockIcon,
    'Plug Connect Fill': PlugConnectFillIcon,
    'FA Calendar Check': FaCalendarCheckIcon,
    'Magnifying Glass': MagnifyingGlassIcon,
    'Spread Sheet File': SpreadSheetFileIcon,
    'Hard Drive Upload': HardDriveUploadIcon,
    'List Bullets Bold': ListBulletsBoldIcon,
    'Mixer Horizontal': MixerHorizontalIcon,
    'Transaction List': TransactionListIcon,
    'Dash Square Dotted': DashSquareDottedIcon,
    'Open External Link': OpenExternalLinkIcon,
    'Flip Vertical Line': FlipVerticalLineIcon,
    'Badge Exclamation': BadgeExclamationIcon,
    'Document File Fill': DocumentFileFillIcon,
    'Shield Exclamation': ShieldExclamationIcon,
    'Badge Question Fill': BadgeQuestionFillIcon,
    'Location Pin Outline': LocationPinOutlineIcon,
    'Question Circle Fill': QuestionCircleFillIcon,
    'Flip Horizontal Line': FlipHorizontalLineIcon,
    'Rotate 90 Degree Left': Rotate90DegreeLeftIcon,
    'Rotate 90 Degree Right': Rotate90DegreeRightIcon,
    'Badge Exclamation Fill': BadgeExclamationFillIcon,
    'Text Strikethrough Light': TextStrikethroughLightIcon,
}

export const RenderIcon = ({
    icon,
    ...props
}: { icon: TIcon } & IconBaseProps) => {
    const FoundIcon = IconMap[icon]

    if (FoundIcon === undefined) return

    return <FoundIcon {...props} />
}
