import { IUserBase } from '../auth'
import { IAuditable, ITimeStamps, TEntityId } from '../common'

export interface IMedia extends ITimeStamps, IAuditable {
    id: TEntityId
    file_name: string
    file_size: number
    file_type: string
    storage_key: string
    url: string
    bucket_name: string
    download_url: string // generated by server not by db
    description?: string
}

export interface IMediaRequest {
    id?: TEntityId
    file_name: string
    file_size: number
    fileType: string
    storageKey: string
    key?: string
    url?: string
    bucketName?: string

    userId?: TEntityId
    user?: IUserBase
}
