import { useCallback } from 'react'

import { useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { z } from 'zod'

import { zodResolver } from '@hookform/resolvers/zod'

import { useGetById as useAccountById } from '@/modules/account'
import { IGeneralLedger } from '@/modules/general-ledger'
import MemberPicker from '@/modules/member-profile/components/member-picker'
import {
    TransactionCreateWithPaymentFormModal,
    useGetById,
    useTransactionShortcuts,
    useUpdateReferenceNumber,
} from '@/modules/transaction'
import { useGetUserSettings } from '@/modules/user-profile'
import { useImagePreview } from '@/store/image-preview-store'
import { useTransactionStore } from '@/store/transaction/transaction-store'

import { MoneyIcon, XIcon } from '@/components/icons'
import LoadingSpinner from '@/components/spinners/loading-spinner'
import { Button } from '@/components/ui/button'
import { Form } from '@/components/ui/form'
import FormFieldWrapper from '@/components/ui/form-field-wrapper'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'

import { useQeueryHookCallback } from '@/hooks/use-query-hook-cb'

import { TEntityId } from '@/types'

import ReferenceNumber from '../input/transaction-reference-number-field'

const updateTransactionOR = z.object({
    reference_number: z.string().min(1, 'Reference number is required'),
    description: z.string().max(250, 'Description is required'),
})

type FormValues = z.infer<typeof updateTransactionOR>

type TransactionFormProps = {
    transactionId: TEntityId
    handleSetTransactionId: (transactionId?: TEntityId) => void
    hasSelectedMember: boolean
    hasSelectedTransactionId: boolean
}
const TransactionForm = ({
    transactionId,
    hasSelectedTransactionId,
    handleSetTransactionId,
    hasSelectedMember,
}: TransactionFormProps) => {
    const queryClient = useQueryClient()
    const {
        settings_accounting_payment_default_value_id,
        settings_accounting_deposit_default_value_id,
        settings_accounting_withdraw_default_value_id,
        userSettingOR,
        settings_payment_type_default_value_id,
    } = useGetUserSettings()

    const {
        selectedMember,
        openSuccessModal,
        focusTypePayment,
        openMemberPicker,
        selectedAccountId,
        isAutoGeneratedOR,
        selectedJointMember,
        openPaymentWithTransactionModal,
        focusedLedger,
        selectedAccount,
        handleResetAll,
        setSelectedMember,
        setFocusTypePayment,
        setOpenMemberPicker,
        setOpenSuccessModal,
        setSelectedAccountId,
        setIsAutoGeneratedOR,
        setTransactionFormSuccess,
        setOpenPaymentWithTransactionModal,
    } = useTransactionStore()

    const { isOpen } = useImagePreview()

    const form = useForm<FormValues>({
        resolver: zodResolver(updateTransactionOR),
        defaultValues: {
            reference_number: userSettingOR,
            description: '',
        },
    })

    const {
        mutate: updateReferenceNumber,
        isPending: isLoadingUpdateReferenceNumber,
    } = useUpdateReferenceNumber()

    const {
        data: transaction,
        isSuccess: isSuccessGetTransaction,
        isError: isErrorGetTransaction,
        error: errorGetTransaction,
    } = useGetById({
        id: transactionId,
        options: { enabled: !!transactionId },
    })

    const handleSuccessGetTransaction = useCallback(() => {
        form.setValue('reference_number', transaction?.reference_number || '')
        form.setValue('description', transaction?.description || '')
        setSelectedMember?.(transaction?.member_profile ?? null)
    }, [form, setSelectedMember, transaction])

    useQeueryHookCallback({
        data: transaction,
        onSuccess: handleSuccessGetTransaction,
        error: errorGetTransaction,
        isError: isErrorGetTransaction,
        isSuccess: isSuccessGetTransaction,
    })

    const referenceNumber = transaction?.reference_number || ''
    const description = transaction?.description || ''

    const onSubmit = form.handleSubmit((values: FormValues) => {
        if (transaction) {
            updateReferenceNumber({
                transactionId: transaction.id,
                reference_number: values.reference_number,
                description: values.description,
            })
        }
    })
    const handleSetOR = () => {
        form.setValue('reference_number', userSettingOR)
    }

    const handleResetForm = () => {
        form.reset({
            reference_number: referenceNumber || '',
            description: description || '',
        })
        setIsAutoGeneratedOR?.(false)
        handleSetOR()
    }
    const handleOnSuccessPaymentCallBack = (transaction: IGeneralLedger) => {
        setTransactionFormSuccess(transaction)
        setOpenSuccessModal(true)
    }

    const referenceNotEqual = form.watch('reference_number') !== referenceNumber
    const descriptionNotEqual = form.watch('description') !== description

    const accountDefaultValue =
        focusTypePayment === 'payment'
            ? settings_accounting_payment_default_value_id || ''
            : focusTypePayment === 'deposit'
              ? settings_accounting_deposit_default_value_id || ''
              : settings_accounting_withdraw_default_value_id || ''

    const { data: account } = useAccountById({
        id: accountDefaultValue,
    })

    const quickPaymentTitle = (
        <div className="flex items-center">
            <MoneyIcon className="mr-2" />
            <span className="font-bold">{`${focusTypePayment?.charAt(0).toUpperCase()}${focusTypePayment?.slice(1)}`}</span>
        </div>
    )

    useTransactionShortcuts({
        hasSelectedMember: hasSelectedMember,
        openPaymentWithTransactionModal,
        openSuccessModal,
        hasSelectedTransactionId: hasSelectedTransactionId,
        setOpenPaymentWithTransactionModal,
        setFocusTypePayment,
        handleResetAll: () => {
            handleResetAll()
            handleSetTransactionId(undefined)
            form.reset()
        },
        setOpenMemberPicker,
        setSelectedMember: () => {
            setSelectedMember(null)
        },
        isMediaOpen: isOpen,
        hasFocusedGeneralLedger: focusedLedger !== undefined,
    })

    return (
        <Form {...form}>
            <div className="hidden">
                <MemberPicker
                    modalState={{
                        open: openMemberPicker,
                        onOpenChange: setOpenMemberPicker,
                    }}
                    onSelect={(selectedMember) => {
                        setSelectedMember(selectedMember)
                        setTimeout(() => {
                            form.setFocus('reference_number')
                        }, 0)
                    }}
                    placeholder="Select Member"
                />
            </div>
            <TransactionCreateWithPaymentFormModal
                open={openPaymentWithTransactionModal}
                title={quickPaymentTitle}
                className="max-w-2xl"
                onOpenChange={setOpenPaymentWithTransactionModal}
                formProps={{
                    transactionId,
                    referenceNumber: form.watch('reference_number'),
                    memberProfileId: selectedMember?.id,
                    memberJointId: selectedJointMember?.id,
                    isReferenceNumberCheck: isAutoGeneratedOR,
                    description: form.watch('description'),
                    account: selectedAccount || account,
                    defaultValues: {
                        entry_date: new Date().toISOString(),
                        account_id: selectedAccountId || accountDefaultValue,
                        payment_type_id:
                            settings_payment_type_default_value_id ?? undefined,
                    },
                    onSuccess(transaction) {
                        queryClient.invalidateQueries({
                            queryKey: [
                                'member-accounting-ledger',
                                'resource-query',
                                'member',
                                transaction.member_profile_id,
                            ],
                        })

                        queryClient.invalidateQueries({
                            queryKey: ['get-transaction-by-id', transactionId],
                        })
                        queryClient.invalidateQueries({
                            queryKey: ['current-transaction-list'],
                        })
                        form.setValue('reference_number', userSettingOR)
                        setOpenPaymentWithTransactionModal(false)
                        setSelectedMember(transaction.member_profile)
                        setSelectedAccountId(undefined)
                        handleSetTransactionId(transaction.transaction_id)
                        handleOnSuccessPaymentCallBack(transaction)
                    },
                }}
            />
            <form onSubmit={onSubmit} className="min-h-fit">
                <div className="flex  items-center h-fit space-x-2 w-full">
                    <FormFieldWrapper
                        control={form.control}
                        name="reference_number"
                        labelClassName="text-xs font-medium text-muted-foreground"
                        render={({ field }) => (
                            <div className="flex flex-col">
                                <Label
                                    className="text-xs font-medium text-muted-foreground"
                                    htmlFor={field.name}
                                >
                                    Reference Number:
                                    <Button
                                        size={'sm'}
                                        variant={'ghost'}
                                        onClick={(e) => {
                                            e.preventDefault()
                                            setIsAutoGeneratedOR?.(
                                                !isAutoGeneratedOR
                                            )
                                            handleSetOR?.()
                                        }}
                                        className="text-muted-foreground text-xs relative hover:bg-transparent"
                                    >
                                        generate OR{' '}
                                        {isAutoGeneratedOR && (
                                            <span className="size-1.5 bg-green-400 absolute right-1 top-2 rounded-full" />
                                        )}
                                    </Button>
                                </Label>
                                <ReferenceNumber
                                    {...field}
                                    id={field.name}
                                    ref={field.ref}
                                    placeholder="Reference Number"
                                    value={field.value || referenceNumber || ''}
                                    onChange={field.onChange}
                                    disabled={
                                        (!referenceNotEqual && !transaction) ||
                                        isAutoGeneratedOR
                                    }
                                />
                            </div>
                        )}
                    />
                    <FormFieldWrapper
                        control={form.control}
                        name="description"
                        className="grow h-full translate-y-1"
                        label="Description"
                        labelClassName="text-xs font-medium text-muted-foreground"
                        render={({ field }) => (
                            <div className="flex space-x-2 ">
                                <Textarea
                                    {...field}
                                    id={field.name}
                                    disabled={!hasSelectedTransactionId}
                                    value={field.value || description || ''}
                                    autoComplete="off"
                                    className="grow h-10 min-h-10 resize-none"
                                    placeholder="Description"
                                />
                                {hasSelectedTransactionId && (
                                    <div className="flex space-x-1">
                                        <Button
                                            variant="destructive"
                                            className=""
                                            disabled={
                                                !referenceNotEqual &&
                                                !descriptionNotEqual
                                            }
                                            size="icon"
                                            onClick={() => handleResetForm?.()}
                                        >
                                            <XIcon className="" />
                                        </Button>
                                        {(referenceNotEqual ||
                                            descriptionNotEqual) && (
                                            <Button
                                                variant="secondary"
                                                className=""
                                                type="submit"
                                                disabled={
                                                    isLoadingUpdateReferenceNumber
                                                }
                                            >
                                                {isLoadingUpdateReferenceNumber ? (
                                                    <LoadingSpinner className="animate-spin" />
                                                ) : (
                                                    'save'
                                                )}
                                            </Button>
                                        )}
                                    </div>
                                )}
                            </div>
                        )}
                    />
                </div>
            </form>
        </Form>
    )
}

export default TransactionForm
