/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as OnboardingRouteImport } from './routes/onboarding/route';
import { Route as AuthRouteImport } from './routes/auth/route';
import { Route as AccountRouteImport } from './routes/account/route';
import { Route as landingRouteImport } from './routes/(landing)/route';
import { Route as AccountIndexImport } from './routes/account/index';
import { Route as landingIndexImport } from './routes/(landing)/index';
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password';
import { Route as AccountSecurityImport } from './routes/account/security';
import { Route as AccountQrImport } from './routes/account/qr';
import { Route as AccountProfileImport } from './routes/account/profile';
import { Route as landingDevelopersImport } from './routes/(landing)/developers';
import { Route as landingContactImport } from './routes/(landing)/contact';
import { Route as landingAboutImport } from './routes/(landing)/about';
import { Route as OrgOrgnameRouteImport } from './routes/org/$orgname.route';
import { Route as AuthPasswordResetResetIdImport } from './routes/auth/password-reset.$resetId';
import { Route as AccountVerifyEmailImport } from './routes/account/verify/email';
import { Route as AccountVerifyContactImport } from './routes/account/verify/contact';
import { Route as OrgOrgnameBranchBranchnameRouteImport } from './routes/org/$orgname.branch.$branchname/route';
import { Route as OrgOrgnameBranchBranchnamecommonFootstepImport } from './routes/org/$orgname.branch.$branchname/(common)/footstep';
import { Route as OrgOrgnameBranchBranchnamecommonDashboardImport } from './routes/org/$orgname.branch.$branchname/(common)/dashboard';
import { Route as OrgOrgnameBranchBranchnameemployeeLoanIndexImport } from './routes/org/$orgname.branch.$branchname/(employee)/loan/index';
import { Route as OrgOrgnameBranchBranchnameemployeeTransactionPaymentTypeImport } from './routes/org/$orgname.branch.$branchname/(employee)/transaction/payment-type';
import { Route as OrgOrgnameBranchBranchnameemployeeTransactionPaymentEntryImport } from './routes/org/$orgname.branch.$branchname/(employee)/transaction/payment-entry';
import { Route as OrgOrgnameBranchBranchnameemployeeLoanLoanApplicationImport } from './routes/org/$orgname.branch.$branchname/(employee)/loan/loan-application';
import { Route as OrgOrgnameBranchBranchnameemployeeAccountingAccountsImport } from './routes/org/$orgname.branch.$branchname/(employee)/accounting/accounts';
import { Route as OrgOrgnameBranchBranchnameemployeeAccountingAccountTypeImport } from './routes/org/$orgname.branch.$branchname/(employee)/accounting/account-type';
import { Route as OrgOrgnameBranchBranchnamemaintenanceUsersMemberIndexImport } from './routes/org/$orgname.branch.$branchname/(maintenance)/users/member/index';
import { Route as OrgOrgnameBranchBranchnamemaintenanceUsersEmployeeIndexImport } from './routes/org/$orgname.branch.$branchname/(maintenance)/users/employee/index';
import { Route as OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberTypeImport } from './routes/org/$orgname.branch.$branchname/(maintenance)/users/member/member-type';
import { Route as OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberOccupationImport } from './routes/org/$orgname.branch.$branchname/(maintenance)/users/member/member-occupation';
import { Route as OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberGenderImport } from './routes/org/$orgname.branch.$branchname/(maintenance)/users/member/member-gender';
import { Route as OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberClassificationImport } from './routes/org/$orgname.branch.$branchname/(maintenance)/users/member/member-classification';
import { Route as OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberCenterImport } from './routes/org/$orgname.branch.$branchname/(maintenance)/users/member/member-center';

// Create Virtual Routes

const AuthSignUpLazyImport = createFileRoute('/auth/sign-up')();
const AuthSignInLazyImport = createFileRoute('/auth/sign-in')();

// Create/Update Routes

const OnboardingRouteRoute = OnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => rootRoute,
} as any);

const AuthRouteRoute = AuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => rootRoute,
} as any);

const AccountRouteRoute = AccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => rootRoute,
} as any);

const landingRouteRoute = landingRouteImport.update({
    id: '/(landing)',
    getParentRoute: () => rootRoute,
} as any);

const AccountIndexRoute = AccountIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountRouteRoute,
} as any);

const landingIndexRoute = landingIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => landingRouteRoute,
} as any);

const AuthSignUpLazyRoute = AuthSignUpLazyImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/auth/sign-up.lazy').then((d) => d.Route));

const AuthSignInLazyRoute = AuthSignInLazyImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/auth/sign-in.lazy').then((d) => d.Route));

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => AuthRouteRoute,
} as any);

const AccountSecurityRoute = AccountSecurityImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AccountRouteRoute,
} as any);

const AccountQrRoute = AccountQrImport.update({
    id: '/qr',
    path: '/qr',
    getParentRoute: () => AccountRouteRoute,
} as any);

const AccountProfileRoute = AccountProfileImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AccountRouteRoute,
} as any);

const landingDevelopersRoute = landingDevelopersImport.update({
    id: '/developers',
    path: '/developers',
    getParentRoute: () => landingRouteRoute,
} as any);

const landingContactRoute = landingContactImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => landingRouteRoute,
} as any);

const landingAboutRoute = landingAboutImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => landingRouteRoute,
} as any);

const OrgOrgnameRouteRoute = OrgOrgnameRouteImport.update({
    id: '/org/$orgname',
    path: '/org/$orgname',
    getParentRoute: () => rootRoute,
} as any);

const AuthPasswordResetResetIdRoute = AuthPasswordResetResetIdImport.update({
    id: '/password-reset/$resetId',
    path: '/password-reset/$resetId',
    getParentRoute: () => AuthRouteRoute,
} as any);

const AccountVerifyEmailRoute = AccountVerifyEmailImport.update({
    id: '/verify/email',
    path: '/verify/email',
    getParentRoute: () => AccountRouteRoute,
} as any);

const AccountVerifyContactRoute = AccountVerifyContactImport.update({
    id: '/verify/contact',
    path: '/verify/contact',
    getParentRoute: () => AccountRouteRoute,
} as any);

const OrgOrgnameBranchBranchnameRouteRoute =
    OrgOrgnameBranchBranchnameRouteImport.update({
        id: '/branch/$branchname',
        path: '/branch/$branchname',
        getParentRoute: () => OrgOrgnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnamecommonFootstepRoute =
    OrgOrgnameBranchBranchnamecommonFootstepImport.update({
        id: '/(common)/footstep',
        path: '/footstep',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnamecommonDashboardRoute =
    OrgOrgnameBranchBranchnamecommonDashboardImport.update({
        id: '/(common)/dashboard',
        path: '/dashboard',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnameemployeeLoanIndexRoute =
    OrgOrgnameBranchBranchnameemployeeLoanIndexImport.update({
        id: '/(employee)/loan/',
        path: '/loan/',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnameemployeeTransactionPaymentTypeRoute =
    OrgOrgnameBranchBranchnameemployeeTransactionPaymentTypeImport.update({
        id: '/(employee)/transaction/payment-type',
        path: '/transaction/payment-type',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnameemployeeTransactionPaymentEntryRoute =
    OrgOrgnameBranchBranchnameemployeeTransactionPaymentEntryImport.update({
        id: '/(employee)/transaction/payment-entry',
        path: '/transaction/payment-entry',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnameemployeeLoanLoanApplicationRoute =
    OrgOrgnameBranchBranchnameemployeeLoanLoanApplicationImport.update({
        id: '/(employee)/loan/loan-application',
        path: '/loan/loan-application',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnameemployeeAccountingAccountsRoute =
    OrgOrgnameBranchBranchnameemployeeAccountingAccountsImport.update({
        id: '/(employee)/accounting/accounts',
        path: '/accounting/accounts',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnameemployeeAccountingAccountTypeRoute =
    OrgOrgnameBranchBranchnameemployeeAccountingAccountTypeImport.update({
        id: '/(employee)/accounting/account-type',
        path: '/accounting/account-type',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnamemaintenanceUsersMemberIndexRoute =
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberIndexImport.update({
        id: '/(maintenance)/users/member/',
        path: '/users/member/',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnamemaintenanceUsersEmployeeIndexRoute =
    OrgOrgnameBranchBranchnamemaintenanceUsersEmployeeIndexImport.update({
        id: '/(maintenance)/users/employee/',
        path: '/users/employee/',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberTypeRoute =
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberTypeImport.update({
        id: '/(maintenance)/users/member/member-type',
        path: '/users/member/member-type',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberOccupationRoute =
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberOccupationImport.update(
        {
            id: '/(maintenance)/users/member/member-occupation',
            path: '/users/member/member-occupation',
            getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
        } as any
    );

const OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberGenderRoute =
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberGenderImport.update({
        id: '/(maintenance)/users/member/member-gender',
        path: '/users/member/member-gender',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

const OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberClassificationRoute =
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberClassificationImport.update(
        {
            id: '/(maintenance)/users/member/member-classification',
            path: '/users/member/member-classification',
            getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
        } as any
    );

const OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberCenterRoute =
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberCenterImport.update({
        id: '/(maintenance)/users/member/member-center',
        path: '/users/member/member-center',
        getParentRoute: () => OrgOrgnameBranchBranchnameRouteRoute,
    } as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/(landing)': {
            id: '/(landing)';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof landingRouteImport;
            parentRoute: typeof rootRoute;
        };
        '/account': {
            id: '/account';
            path: '/account';
            fullPath: '/account';
            preLoaderRoute: typeof AccountRouteImport;
            parentRoute: typeof rootRoute;
        };
        '/auth': {
            id: '/auth';
            path: '/auth';
            fullPath: '/auth';
            preLoaderRoute: typeof AuthRouteImport;
            parentRoute: typeof rootRoute;
        };
        '/onboarding': {
            id: '/onboarding';
            path: '/onboarding';
            fullPath: '/onboarding';
            preLoaderRoute: typeof OnboardingRouteImport;
            parentRoute: typeof rootRoute;
        };
        '/org/$orgname': {
            id: '/org/$orgname';
            path: '/org/$orgname';
            fullPath: '/org/$orgname';
            preLoaderRoute: typeof OrgOrgnameRouteImport;
            parentRoute: typeof rootRoute;
        };
        '/(landing)/about': {
            id: '/(landing)/about';
            path: '/about';
            fullPath: '/about';
            preLoaderRoute: typeof landingAboutImport;
            parentRoute: typeof landingRouteImport;
        };
        '/(landing)/contact': {
            id: '/(landing)/contact';
            path: '/contact';
            fullPath: '/contact';
            preLoaderRoute: typeof landingContactImport;
            parentRoute: typeof landingRouteImport;
        };
        '/(landing)/developers': {
            id: '/(landing)/developers';
            path: '/developers';
            fullPath: '/developers';
            preLoaderRoute: typeof landingDevelopersImport;
            parentRoute: typeof landingRouteImport;
        };
        '/account/profile': {
            id: '/account/profile';
            path: '/profile';
            fullPath: '/account/profile';
            preLoaderRoute: typeof AccountProfileImport;
            parentRoute: typeof AccountRouteImport;
        };
        '/account/qr': {
            id: '/account/qr';
            path: '/qr';
            fullPath: '/account/qr';
            preLoaderRoute: typeof AccountQrImport;
            parentRoute: typeof AccountRouteImport;
        };
        '/account/security': {
            id: '/account/security';
            path: '/security';
            fullPath: '/account/security';
            preLoaderRoute: typeof AccountSecurityImport;
            parentRoute: typeof AccountRouteImport;
        };
        '/auth/forgot-password': {
            id: '/auth/forgot-password';
            path: '/forgot-password';
            fullPath: '/auth/forgot-password';
            preLoaderRoute: typeof AuthForgotPasswordImport;
            parentRoute: typeof AuthRouteImport;
        };
        '/auth/sign-in': {
            id: '/auth/sign-in';
            path: '/sign-in';
            fullPath: '/auth/sign-in';
            preLoaderRoute: typeof AuthSignInLazyImport;
            parentRoute: typeof AuthRouteImport;
        };
        '/auth/sign-up': {
            id: '/auth/sign-up';
            path: '/sign-up';
            fullPath: '/auth/sign-up';
            preLoaderRoute: typeof AuthSignUpLazyImport;
            parentRoute: typeof AuthRouteImport;
        };
        '/(landing)/': {
            id: '/(landing)/';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof landingIndexImport;
            parentRoute: typeof landingRouteImport;
        };
        '/account/': {
            id: '/account/';
            path: '/';
            fullPath: '/account/';
            preLoaderRoute: typeof AccountIndexImport;
            parentRoute: typeof AccountRouteImport;
        };
        '/account/verify/contact': {
            id: '/account/verify/contact';
            path: '/verify/contact';
            fullPath: '/account/verify/contact';
            preLoaderRoute: typeof AccountVerifyContactImport;
            parentRoute: typeof AccountRouteImport;
        };
        '/account/verify/email': {
            id: '/account/verify/email';
            path: '/verify/email';
            fullPath: '/account/verify/email';
            preLoaderRoute: typeof AccountVerifyEmailImport;
            parentRoute: typeof AccountRouteImport;
        };
        '/auth/password-reset/$resetId': {
            id: '/auth/password-reset/$resetId';
            path: '/password-reset/$resetId';
            fullPath: '/auth/password-reset/$resetId';
            preLoaderRoute: typeof AuthPasswordResetResetIdImport;
            parentRoute: typeof AuthRouteImport;
        };
        '/org/$orgname/branch/$branchname': {
            id: '/org/$orgname/branch/$branchname';
            path: '/branch/$branchname';
            fullPath: '/org/$orgname/branch/$branchname';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
            parentRoute: typeof OrgOrgnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(common)/dashboard': {
            id: '/org/$orgname/branch/$branchname/(common)/dashboard';
            path: '/dashboard';
            fullPath: '/org/$orgname/branch/$branchname/dashboard';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnamecommonDashboardImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(common)/footstep': {
            id: '/org/$orgname/branch/$branchname/(common)/footstep';
            path: '/footstep';
            fullPath: '/org/$orgname/branch/$branchname/footstep';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnamecommonFootstepImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(employee)/accounting/account-type': {
            id: '/org/$orgname/branch/$branchname/(employee)/accounting/account-type';
            path: '/accounting/account-type';
            fullPath: '/org/$orgname/branch/$branchname/accounting/account-type';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnameemployeeAccountingAccountTypeImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(employee)/accounting/accounts': {
            id: '/org/$orgname/branch/$branchname/(employee)/accounting/accounts';
            path: '/accounting/accounts';
            fullPath: '/org/$orgname/branch/$branchname/accounting/accounts';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnameemployeeAccountingAccountsImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(employee)/loan/loan-application': {
            id: '/org/$orgname/branch/$branchname/(employee)/loan/loan-application';
            path: '/loan/loan-application';
            fullPath: '/org/$orgname/branch/$branchname/loan/loan-application';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnameemployeeLoanLoanApplicationImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(employee)/transaction/payment-entry': {
            id: '/org/$orgname/branch/$branchname/(employee)/transaction/payment-entry';
            path: '/transaction/payment-entry';
            fullPath: '/org/$orgname/branch/$branchname/transaction/payment-entry';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnameemployeeTransactionPaymentEntryImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(employee)/transaction/payment-type': {
            id: '/org/$orgname/branch/$branchname/(employee)/transaction/payment-type';
            path: '/transaction/payment-type';
            fullPath: '/org/$orgname/branch/$branchname/transaction/payment-type';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnameemployeeTransactionPaymentTypeImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(employee)/loan/': {
            id: '/org/$orgname/branch/$branchname/(employee)/loan/';
            path: '/loan';
            fullPath: '/org/$orgname/branch/$branchname/loan';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnameemployeeLoanIndexImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-center': {
            id: '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-center';
            path: '/users/member/member-center';
            fullPath: '/org/$orgname/branch/$branchname/users/member/member-center';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberCenterImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-classification': {
            id: '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-classification';
            path: '/users/member/member-classification';
            fullPath: '/org/$orgname/branch/$branchname/users/member/member-classification';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberClassificationImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-gender': {
            id: '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-gender';
            path: '/users/member/member-gender';
            fullPath: '/org/$orgname/branch/$branchname/users/member/member-gender';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberGenderImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-occupation': {
            id: '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-occupation';
            path: '/users/member/member-occupation';
            fullPath: '/org/$orgname/branch/$branchname/users/member/member-occupation';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberOccupationImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-type': {
            id: '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-type';
            path: '/users/member/member-type';
            fullPath: '/org/$orgname/branch/$branchname/users/member/member-type';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberTypeImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(maintenance)/users/employee/': {
            id: '/org/$orgname/branch/$branchname/(maintenance)/users/employee/';
            path: '/users/employee';
            fullPath: '/org/$orgname/branch/$branchname/users/employee';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersEmployeeIndexImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
        '/org/$orgname/branch/$branchname/(maintenance)/users/member/': {
            id: '/org/$orgname/branch/$branchname/(maintenance)/users/member/';
            path: '/users/member';
            fullPath: '/org/$orgname/branch/$branchname/users/member';
            preLoaderRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberIndexImport;
            parentRoute: typeof OrgOrgnameBranchBranchnameRouteImport;
        };
    }
}

// Create and export the route tree

interface landingRouteRouteChildren {
    landingAboutRoute: typeof landingAboutRoute;
    landingContactRoute: typeof landingContactRoute;
    landingDevelopersRoute: typeof landingDevelopersRoute;
    landingIndexRoute: typeof landingIndexRoute;
}

const landingRouteRouteChildren: landingRouteRouteChildren = {
    landingAboutRoute: landingAboutRoute,
    landingContactRoute: landingContactRoute,
    landingDevelopersRoute: landingDevelopersRoute,
    landingIndexRoute: landingIndexRoute,
};

const landingRouteRouteWithChildren = landingRouteRoute._addFileChildren(
    landingRouteRouteChildren
);

interface AccountRouteRouteChildren {
    AccountProfileRoute: typeof AccountProfileRoute;
    AccountQrRoute: typeof AccountQrRoute;
    AccountSecurityRoute: typeof AccountSecurityRoute;
    AccountIndexRoute: typeof AccountIndexRoute;
    AccountVerifyContactRoute: typeof AccountVerifyContactRoute;
    AccountVerifyEmailRoute: typeof AccountVerifyEmailRoute;
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
    AccountProfileRoute: AccountProfileRoute,
    AccountQrRoute: AccountQrRoute,
    AccountSecurityRoute: AccountSecurityRoute,
    AccountIndexRoute: AccountIndexRoute,
    AccountVerifyContactRoute: AccountVerifyContactRoute,
    AccountVerifyEmailRoute: AccountVerifyEmailRoute,
};

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
    AccountRouteRouteChildren
);

interface AuthRouteRouteChildren {
    AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
    AuthSignInLazyRoute: typeof AuthSignInLazyRoute;
    AuthSignUpLazyRoute: typeof AuthSignUpLazyRoute;
    AuthPasswordResetResetIdRoute: typeof AuthPasswordResetResetIdRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
    AuthForgotPasswordRoute: AuthForgotPasswordRoute,
    AuthSignInLazyRoute: AuthSignInLazyRoute,
    AuthSignUpLazyRoute: AuthSignUpLazyRoute,
    AuthPasswordResetResetIdRoute: AuthPasswordResetResetIdRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
    AuthRouteRouteChildren
);

interface OrgOrgnameBranchBranchnameRouteRouteChildren {
    OrgOrgnameBranchBranchnamecommonDashboardRoute: typeof OrgOrgnameBranchBranchnamecommonDashboardRoute;
    OrgOrgnameBranchBranchnamecommonFootstepRoute: typeof OrgOrgnameBranchBranchnamecommonFootstepRoute;
    OrgOrgnameBranchBranchnameemployeeAccountingAccountTypeRoute: typeof OrgOrgnameBranchBranchnameemployeeAccountingAccountTypeRoute;
    OrgOrgnameBranchBranchnameemployeeAccountingAccountsRoute: typeof OrgOrgnameBranchBranchnameemployeeAccountingAccountsRoute;
    OrgOrgnameBranchBranchnameemployeeLoanLoanApplicationRoute: typeof OrgOrgnameBranchBranchnameemployeeLoanLoanApplicationRoute;
    OrgOrgnameBranchBranchnameemployeeTransactionPaymentEntryRoute: typeof OrgOrgnameBranchBranchnameemployeeTransactionPaymentEntryRoute;
    OrgOrgnameBranchBranchnameemployeeTransactionPaymentTypeRoute: typeof OrgOrgnameBranchBranchnameemployeeTransactionPaymentTypeRoute;
    OrgOrgnameBranchBranchnameemployeeLoanIndexRoute: typeof OrgOrgnameBranchBranchnameemployeeLoanIndexRoute;
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberCenterRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberCenterRoute;
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberClassificationRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberClassificationRoute;
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberGenderRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberGenderRoute;
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberOccupationRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberOccupationRoute;
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberTypeRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberTypeRoute;
    OrgOrgnameBranchBranchnamemaintenanceUsersEmployeeIndexRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersEmployeeIndexRoute;
    OrgOrgnameBranchBranchnamemaintenanceUsersMemberIndexRoute: typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberIndexRoute;
}

const OrgOrgnameBranchBranchnameRouteRouteChildren: OrgOrgnameBranchBranchnameRouteRouteChildren =
    {
        OrgOrgnameBranchBranchnamecommonDashboardRoute:
            OrgOrgnameBranchBranchnamecommonDashboardRoute,
        OrgOrgnameBranchBranchnamecommonFootstepRoute:
            OrgOrgnameBranchBranchnamecommonFootstepRoute,
        OrgOrgnameBranchBranchnameemployeeAccountingAccountTypeRoute:
            OrgOrgnameBranchBranchnameemployeeAccountingAccountTypeRoute,
        OrgOrgnameBranchBranchnameemployeeAccountingAccountsRoute:
            OrgOrgnameBranchBranchnameemployeeAccountingAccountsRoute,
        OrgOrgnameBranchBranchnameemployeeLoanLoanApplicationRoute:
            OrgOrgnameBranchBranchnameemployeeLoanLoanApplicationRoute,
        OrgOrgnameBranchBranchnameemployeeTransactionPaymentEntryRoute:
            OrgOrgnameBranchBranchnameemployeeTransactionPaymentEntryRoute,
        OrgOrgnameBranchBranchnameemployeeTransactionPaymentTypeRoute:
            OrgOrgnameBranchBranchnameemployeeTransactionPaymentTypeRoute,
        OrgOrgnameBranchBranchnameemployeeLoanIndexRoute:
            OrgOrgnameBranchBranchnameemployeeLoanIndexRoute,
        OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberCenterRoute:
            OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberCenterRoute,
        OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberClassificationRoute:
            OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberClassificationRoute,
        OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberGenderRoute:
            OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberGenderRoute,
        OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberOccupationRoute:
            OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberOccupationRoute,
        OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberTypeRoute:
            OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberTypeRoute,
        OrgOrgnameBranchBranchnamemaintenanceUsersEmployeeIndexRoute:
            OrgOrgnameBranchBranchnamemaintenanceUsersEmployeeIndexRoute,
        OrgOrgnameBranchBranchnamemaintenanceUsersMemberIndexRoute:
            OrgOrgnameBranchBranchnamemaintenanceUsersMemberIndexRoute,
    };

const OrgOrgnameBranchBranchnameRouteRouteWithChildren =
    OrgOrgnameBranchBranchnameRouteRoute._addFileChildren(
        OrgOrgnameBranchBranchnameRouteRouteChildren
    );

interface OrgOrgnameRouteRouteChildren {
    OrgOrgnameBranchBranchnameRouteRoute: typeof OrgOrgnameBranchBranchnameRouteRouteWithChildren;
}

const OrgOrgnameRouteRouteChildren: OrgOrgnameRouteRouteChildren = {
    OrgOrgnameBranchBranchnameRouteRoute:
        OrgOrgnameBranchBranchnameRouteRouteWithChildren,
};

const OrgOrgnameRouteRouteWithChildren = OrgOrgnameRouteRoute._addFileChildren(
    OrgOrgnameRouteRouteChildren
);

export interface FileRoutesByFullPath {
    '/': typeof landingIndexRoute;
    '/account': typeof AccountRouteRouteWithChildren;
    '/auth': typeof AuthRouteRouteWithChildren;
    '/onboarding': typeof OnboardingRouteRoute;
    '/org/$orgname': typeof OrgOrgnameRouteRouteWithChildren;
    '/about': typeof landingAboutRoute;
    '/contact': typeof landingContactRoute;
    '/developers': typeof landingDevelopersRoute;
    '/account/profile': typeof AccountProfileRoute;
    '/account/qr': typeof AccountQrRoute;
    '/account/security': typeof AccountSecurityRoute;
    '/auth/forgot-password': typeof AuthForgotPasswordRoute;
    '/auth/sign-in': typeof AuthSignInLazyRoute;
    '/auth/sign-up': typeof AuthSignUpLazyRoute;
    '/account/': typeof AccountIndexRoute;
    '/account/verify/contact': typeof AccountVerifyContactRoute;
    '/account/verify/email': typeof AccountVerifyEmailRoute;
    '/auth/password-reset/$resetId': typeof AuthPasswordResetResetIdRoute;
    '/org/$orgname/branch/$branchname': typeof OrgOrgnameBranchBranchnameRouteRouteWithChildren;
    '/org/$orgname/branch/$branchname/dashboard': typeof OrgOrgnameBranchBranchnamecommonDashboardRoute;
    '/org/$orgname/branch/$branchname/footstep': typeof OrgOrgnameBranchBranchnamecommonFootstepRoute;
    '/org/$orgname/branch/$branchname/accounting/account-type': typeof OrgOrgnameBranchBranchnameemployeeAccountingAccountTypeRoute;
    '/org/$orgname/branch/$branchname/accounting/accounts': typeof OrgOrgnameBranchBranchnameemployeeAccountingAccountsRoute;
    '/org/$orgname/branch/$branchname/loan/loan-application': typeof OrgOrgnameBranchBranchnameemployeeLoanLoanApplicationRoute;
    '/org/$orgname/branch/$branchname/transaction/payment-entry': typeof OrgOrgnameBranchBranchnameemployeeTransactionPaymentEntryRoute;
    '/org/$orgname/branch/$branchname/transaction/payment-type': typeof OrgOrgnameBranchBranchnameemployeeTransactionPaymentTypeRoute;
    '/org/$orgname/branch/$branchname/loan': typeof OrgOrgnameBranchBranchnameemployeeLoanIndexRoute;
    '/org/$orgname/branch/$branchname/users/member/member-center': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberCenterRoute;
    '/org/$orgname/branch/$branchname/users/member/member-classification': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberClassificationRoute;
    '/org/$orgname/branch/$branchname/users/member/member-gender': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberGenderRoute;
    '/org/$orgname/branch/$branchname/users/member/member-occupation': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberOccupationRoute;
    '/org/$orgname/branch/$branchname/users/member/member-type': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberTypeRoute;
    '/org/$orgname/branch/$branchname/users/employee': typeof OrgOrgnameBranchBranchnamemaintenanceUsersEmployeeIndexRoute;
    '/org/$orgname/branch/$branchname/users/member': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberIndexRoute;
}

export interface FileRoutesByTo {
    '/auth': typeof AuthRouteRouteWithChildren;
    '/onboarding': typeof OnboardingRouteRoute;
    '/org/$orgname': typeof OrgOrgnameRouteRouteWithChildren;
    '/about': typeof landingAboutRoute;
    '/contact': typeof landingContactRoute;
    '/developers': typeof landingDevelopersRoute;
    '/account/profile': typeof AccountProfileRoute;
    '/account/qr': typeof AccountQrRoute;
    '/account/security': typeof AccountSecurityRoute;
    '/auth/forgot-password': typeof AuthForgotPasswordRoute;
    '/auth/sign-in': typeof AuthSignInLazyRoute;
    '/auth/sign-up': typeof AuthSignUpLazyRoute;
    '/': typeof landingIndexRoute;
    '/account': typeof AccountIndexRoute;
    '/account/verify/contact': typeof AccountVerifyContactRoute;
    '/account/verify/email': typeof AccountVerifyEmailRoute;
    '/auth/password-reset/$resetId': typeof AuthPasswordResetResetIdRoute;
    '/org/$orgname/branch/$branchname': typeof OrgOrgnameBranchBranchnameRouteRouteWithChildren;
    '/org/$orgname/branch/$branchname/dashboard': typeof OrgOrgnameBranchBranchnamecommonDashboardRoute;
    '/org/$orgname/branch/$branchname/footstep': typeof OrgOrgnameBranchBranchnamecommonFootstepRoute;
    '/org/$orgname/branch/$branchname/accounting/account-type': typeof OrgOrgnameBranchBranchnameemployeeAccountingAccountTypeRoute;
    '/org/$orgname/branch/$branchname/accounting/accounts': typeof OrgOrgnameBranchBranchnameemployeeAccountingAccountsRoute;
    '/org/$orgname/branch/$branchname/loan/loan-application': typeof OrgOrgnameBranchBranchnameemployeeLoanLoanApplicationRoute;
    '/org/$orgname/branch/$branchname/transaction/payment-entry': typeof OrgOrgnameBranchBranchnameemployeeTransactionPaymentEntryRoute;
    '/org/$orgname/branch/$branchname/transaction/payment-type': typeof OrgOrgnameBranchBranchnameemployeeTransactionPaymentTypeRoute;
    '/org/$orgname/branch/$branchname/loan': typeof OrgOrgnameBranchBranchnameemployeeLoanIndexRoute;
    '/org/$orgname/branch/$branchname/users/member/member-center': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberCenterRoute;
    '/org/$orgname/branch/$branchname/users/member/member-classification': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberClassificationRoute;
    '/org/$orgname/branch/$branchname/users/member/member-gender': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberGenderRoute;
    '/org/$orgname/branch/$branchname/users/member/member-occupation': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberOccupationRoute;
    '/org/$orgname/branch/$branchname/users/member/member-type': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberTypeRoute;
    '/org/$orgname/branch/$branchname/users/employee': typeof OrgOrgnameBranchBranchnamemaintenanceUsersEmployeeIndexRoute;
    '/org/$orgname/branch/$branchname/users/member': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberIndexRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    '/(landing)': typeof landingRouteRouteWithChildren;
    '/account': typeof AccountRouteRouteWithChildren;
    '/auth': typeof AuthRouteRouteWithChildren;
    '/onboarding': typeof OnboardingRouteRoute;
    '/org/$orgname': typeof OrgOrgnameRouteRouteWithChildren;
    '/(landing)/about': typeof landingAboutRoute;
    '/(landing)/contact': typeof landingContactRoute;
    '/(landing)/developers': typeof landingDevelopersRoute;
    '/account/profile': typeof AccountProfileRoute;
    '/account/qr': typeof AccountQrRoute;
    '/account/security': typeof AccountSecurityRoute;
    '/auth/forgot-password': typeof AuthForgotPasswordRoute;
    '/auth/sign-in': typeof AuthSignInLazyRoute;
    '/auth/sign-up': typeof AuthSignUpLazyRoute;
    '/(landing)/': typeof landingIndexRoute;
    '/account/': typeof AccountIndexRoute;
    '/account/verify/contact': typeof AccountVerifyContactRoute;
    '/account/verify/email': typeof AccountVerifyEmailRoute;
    '/auth/password-reset/$resetId': typeof AuthPasswordResetResetIdRoute;
    '/org/$orgname/branch/$branchname': typeof OrgOrgnameBranchBranchnameRouteRouteWithChildren;
    '/org/$orgname/branch/$branchname/(common)/dashboard': typeof OrgOrgnameBranchBranchnamecommonDashboardRoute;
    '/org/$orgname/branch/$branchname/(common)/footstep': typeof OrgOrgnameBranchBranchnamecommonFootstepRoute;
    '/org/$orgname/branch/$branchname/(employee)/accounting/account-type': typeof OrgOrgnameBranchBranchnameemployeeAccountingAccountTypeRoute;
    '/org/$orgname/branch/$branchname/(employee)/accounting/accounts': typeof OrgOrgnameBranchBranchnameemployeeAccountingAccountsRoute;
    '/org/$orgname/branch/$branchname/(employee)/loan/loan-application': typeof OrgOrgnameBranchBranchnameemployeeLoanLoanApplicationRoute;
    '/org/$orgname/branch/$branchname/(employee)/transaction/payment-entry': typeof OrgOrgnameBranchBranchnameemployeeTransactionPaymentEntryRoute;
    '/org/$orgname/branch/$branchname/(employee)/transaction/payment-type': typeof OrgOrgnameBranchBranchnameemployeeTransactionPaymentTypeRoute;
    '/org/$orgname/branch/$branchname/(employee)/loan/': typeof OrgOrgnameBranchBranchnameemployeeLoanIndexRoute;
    '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-center': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberCenterRoute;
    '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-classification': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberClassificationRoute;
    '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-gender': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberGenderRoute;
    '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-occupation': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberOccupationRoute;
    '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-type': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberMemberTypeRoute;
    '/org/$orgname/branch/$branchname/(maintenance)/users/employee/': typeof OrgOrgnameBranchBranchnamemaintenanceUsersEmployeeIndexRoute;
    '/org/$orgname/branch/$branchname/(maintenance)/users/member/': typeof OrgOrgnameBranchBranchnamemaintenanceUsersMemberIndexRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | '/'
        | '/account'
        | '/auth'
        | '/onboarding'
        | '/org/$orgname'
        | '/about'
        | '/contact'
        | '/developers'
        | '/account/profile'
        | '/account/qr'
        | '/account/security'
        | '/auth/forgot-password'
        | '/auth/sign-in'
        | '/auth/sign-up'
        | '/account/'
        | '/account/verify/contact'
        | '/account/verify/email'
        | '/auth/password-reset/$resetId'
        | '/org/$orgname/branch/$branchname'
        | '/org/$orgname/branch/$branchname/dashboard'
        | '/org/$orgname/branch/$branchname/footstep'
        | '/org/$orgname/branch/$branchname/accounting/account-type'
        | '/org/$orgname/branch/$branchname/accounting/accounts'
        | '/org/$orgname/branch/$branchname/loan/loan-application'
        | '/org/$orgname/branch/$branchname/transaction/payment-entry'
        | '/org/$orgname/branch/$branchname/transaction/payment-type'
        | '/org/$orgname/branch/$branchname/loan'
        | '/org/$orgname/branch/$branchname/users/member/member-center'
        | '/org/$orgname/branch/$branchname/users/member/member-classification'
        | '/org/$orgname/branch/$branchname/users/member/member-gender'
        | '/org/$orgname/branch/$branchname/users/member/member-occupation'
        | '/org/$orgname/branch/$branchname/users/member/member-type'
        | '/org/$orgname/branch/$branchname/users/employee'
        | '/org/$orgname/branch/$branchname/users/member';
    fileRoutesByTo: FileRoutesByTo;
    to:
        | '/auth'
        | '/onboarding'
        | '/org/$orgname'
        | '/about'
        | '/contact'
        | '/developers'
        | '/account/profile'
        | '/account/qr'
        | '/account/security'
        | '/auth/forgot-password'
        | '/auth/sign-in'
        | '/auth/sign-up'
        | '/'
        | '/account'
        | '/account/verify/contact'
        | '/account/verify/email'
        | '/auth/password-reset/$resetId'
        | '/org/$orgname/branch/$branchname'
        | '/org/$orgname/branch/$branchname/dashboard'
        | '/org/$orgname/branch/$branchname/footstep'
        | '/org/$orgname/branch/$branchname/accounting/account-type'
        | '/org/$orgname/branch/$branchname/accounting/accounts'
        | '/org/$orgname/branch/$branchname/loan/loan-application'
        | '/org/$orgname/branch/$branchname/transaction/payment-entry'
        | '/org/$orgname/branch/$branchname/transaction/payment-type'
        | '/org/$orgname/branch/$branchname/loan'
        | '/org/$orgname/branch/$branchname/users/member/member-center'
        | '/org/$orgname/branch/$branchname/users/member/member-classification'
        | '/org/$orgname/branch/$branchname/users/member/member-gender'
        | '/org/$orgname/branch/$branchname/users/member/member-occupation'
        | '/org/$orgname/branch/$branchname/users/member/member-type'
        | '/org/$orgname/branch/$branchname/users/employee'
        | '/org/$orgname/branch/$branchname/users/member';
    id:
        | '__root__'
        | '/(landing)'
        | '/account'
        | '/auth'
        | '/onboarding'
        | '/org/$orgname'
        | '/(landing)/about'
        | '/(landing)/contact'
        | '/(landing)/developers'
        | '/account/profile'
        | '/account/qr'
        | '/account/security'
        | '/auth/forgot-password'
        | '/auth/sign-in'
        | '/auth/sign-up'
        | '/(landing)/'
        | '/account/'
        | '/account/verify/contact'
        | '/account/verify/email'
        | '/auth/password-reset/$resetId'
        | '/org/$orgname/branch/$branchname'
        | '/org/$orgname/branch/$branchname/(common)/dashboard'
        | '/org/$orgname/branch/$branchname/(common)/footstep'
        | '/org/$orgname/branch/$branchname/(employee)/accounting/account-type'
        | '/org/$orgname/branch/$branchname/(employee)/accounting/accounts'
        | '/org/$orgname/branch/$branchname/(employee)/loan/loan-application'
        | '/org/$orgname/branch/$branchname/(employee)/transaction/payment-entry'
        | '/org/$orgname/branch/$branchname/(employee)/transaction/payment-type'
        | '/org/$orgname/branch/$branchname/(employee)/loan/'
        | '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-center'
        | '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-classification'
        | '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-gender'
        | '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-occupation'
        | '/org/$orgname/branch/$branchname/(maintenance)/users/member/member-type'
        | '/org/$orgname/branch/$branchname/(maintenance)/users/employee/'
        | '/org/$orgname/branch/$branchname/(maintenance)/users/member/';
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    landingRouteRoute: typeof landingRouteRouteWithChildren;
    AccountRouteRoute: typeof AccountRouteRouteWithChildren;
    AuthRouteRoute: typeof AuthRouteRouteWithChildren;
    OnboardingRouteRoute: typeof OnboardingRouteRoute;
    OrgOrgnameRouteRoute: typeof OrgOrgnameRouteRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
    landingRouteRoute: landingRouteRouteWithChildren,
    AccountRouteRoute: AccountRouteRouteWithChildren,
    AuthRouteRoute: AuthRouteRouteWithChildren,
    OnboardingRouteRoute: OnboardingRouteRoute,
    OrgOrgnameRouteRoute: OrgOrgnameRouteRouteWithChildren,
};

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(landing)",
        "/account",
        "/auth",
        "/onboarding",
        "/org/$orgname"
      ]
    },
    "/(landing)": {
      "filePath": "(landing)/route.tsx",
      "children": [
        "/(landing)/about",
        "/(landing)/contact",
        "/(landing)/developers",
        "/(landing)/"
      ]
    },
    "/account": {
      "filePath": "account/route.tsx",
      "children": [
        "/account/profile",
        "/account/qr",
        "/account/security",
        "/account/",
        "/account/verify/contact",
        "/account/verify/email"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/forgot-password",
        "/auth/sign-in",
        "/auth/sign-up",
        "/auth/password-reset/$resetId"
      ]
    },
    "/onboarding": {
      "filePath": "onboarding/route.tsx"
    },
    "/org/$orgname": {
      "filePath": "org/$orgname.route.tsx",
      "children": [
        "/org/$orgname/branch/$branchname"
      ]
    },
    "/(landing)/about": {
      "filePath": "(landing)/about.tsx",
      "parent": "/(landing)"
    },
    "/(landing)/contact": {
      "filePath": "(landing)/contact.tsx",
      "parent": "/(landing)"
    },
    "/(landing)/developers": {
      "filePath": "(landing)/developers.tsx",
      "parent": "/(landing)"
    },
    "/account/profile": {
      "filePath": "account/profile.tsx",
      "parent": "/account"
    },
    "/account/qr": {
      "filePath": "account/qr.tsx",
      "parent": "/account"
    },
    "/account/security": {
      "filePath": "account/security.tsx",
      "parent": "/account"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx",
      "parent": "/auth"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.lazy.tsx",
      "parent": "/auth"
    },
    "/(landing)/": {
      "filePath": "(landing)/index.tsx",
      "parent": "/(landing)"
    },
    "/account/": {
      "filePath": "account/index.tsx",
      "parent": "/account"
    },
    "/account/verify/contact": {
      "filePath": "account/verify/contact.tsx",
      "parent": "/account"
    },
    "/account/verify/email": {
      "filePath": "account/verify/email.tsx",
      "parent": "/account"
    },
    "/auth/password-reset/$resetId": {
      "filePath": "auth/password-reset.$resetId.tsx",
      "parent": "/auth"
    },
    "/org/$orgname/branch/$branchname": {
      "filePath": "org/$orgname.branch.$branchname/route.tsx",
      "parent": "/org/$orgname",
      "children": [
        "/org/$orgname/branch/$branchname/(common)/dashboard",
        "/org/$orgname/branch/$branchname/(common)/footstep",
        "/org/$orgname/branch/$branchname/(employee)/accounting/account-type",
        "/org/$orgname/branch/$branchname/(employee)/accounting/accounts",
        "/org/$orgname/branch/$branchname/(employee)/loan/loan-application",
        "/org/$orgname/branch/$branchname/(employee)/transaction/payment-entry",
        "/org/$orgname/branch/$branchname/(employee)/transaction/payment-type",
        "/org/$orgname/branch/$branchname/(employee)/loan/",
        "/org/$orgname/branch/$branchname/(maintenance)/users/member/member-center",
        "/org/$orgname/branch/$branchname/(maintenance)/users/member/member-classification",
        "/org/$orgname/branch/$branchname/(maintenance)/users/member/member-gender",
        "/org/$orgname/branch/$branchname/(maintenance)/users/member/member-occupation",
        "/org/$orgname/branch/$branchname/(maintenance)/users/member/member-type",
        "/org/$orgname/branch/$branchname/(maintenance)/users/employee/",
        "/org/$orgname/branch/$branchname/(maintenance)/users/member/"
      ]
    },
    "/org/$orgname/branch/$branchname/(common)/dashboard": {
      "filePath": "org/$orgname.branch.$branchname/(common)/dashboard.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(common)/footstep": {
      "filePath": "org/$orgname.branch.$branchname/(common)/footstep.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(employee)/accounting/account-type": {
      "filePath": "org/$orgname.branch.$branchname/(employee)/accounting/account-type.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(employee)/accounting/accounts": {
      "filePath": "org/$orgname.branch.$branchname/(employee)/accounting/accounts.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(employee)/loan/loan-application": {
      "filePath": "org/$orgname.branch.$branchname/(employee)/loan/loan-application.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(employee)/transaction/payment-entry": {
      "filePath": "org/$orgname.branch.$branchname/(employee)/transaction/payment-entry.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(employee)/transaction/payment-type": {
      "filePath": "org/$orgname.branch.$branchname/(employee)/transaction/payment-type.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(employee)/loan/": {
      "filePath": "org/$orgname.branch.$branchname/(employee)/loan/index.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(maintenance)/users/member/member-center": {
      "filePath": "org/$orgname.branch.$branchname/(maintenance)/users/member/member-center.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(maintenance)/users/member/member-classification": {
      "filePath": "org/$orgname.branch.$branchname/(maintenance)/users/member/member-classification.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(maintenance)/users/member/member-gender": {
      "filePath": "org/$orgname.branch.$branchname/(maintenance)/users/member/member-gender.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(maintenance)/users/member/member-occupation": {
      "filePath": "org/$orgname.branch.$branchname/(maintenance)/users/member/member-occupation.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(maintenance)/users/member/member-type": {
      "filePath": "org/$orgname.branch.$branchname/(maintenance)/users/member/member-type.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(maintenance)/users/employee/": {
      "filePath": "org/$orgname.branch.$branchname/(maintenance)/users/employee/index.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    },
    "/org/$orgname/branch/$branchname/(maintenance)/users/member/": {
      "filePath": "org/$orgname.branch.$branchname/(maintenance)/users/member/index.tsx",
      "parent": "/org/$orgname/branch/$branchname"
    }
  }
}
ROUTE_MANIFEST_END */
