name: Quality Checks Pipeline

permissions:
  contents: read

on:
    push:
        branches:
            - staging
            - main
            - development
    pull_request:
        branches:
            - staging
            - main
            - development

jobs:
    code_quality:

        name: Code Quality CI
        runs-on: ubuntu-latest

        steps:
            - name: 📝 Checkout code
              uses: actions/checkout@v3

            - name: 🛠️ Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22.18.0"

            - name: 📦 Install bun
              run: npm i -g bun@1.2.20

            - name: 📦 Install dependencies
              run: bun install

            - name: 🔍🧹 Code Check
              run: bun run dick

            - name: 🧪 Run Tests
              run: bun vitest run

            - name: 🏁 Run Build
              run: bun run build
